package test

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/GabrielNunesIT/gotya"
	"github.com/GabrielNunesIT/gotya/ast"
	"github.com/GabrielNunesIT/gotya/compiler"
	"github.com/GabrielNunesIT/gotya/generator/golang"
	"github.com/GabrielNunesIT/gotya/generator/protobuf"
	"github.com/GabrielNunesIT/gotya/parser"
	"github.com/GabrielNunesIT/gotya/parser/lexer"
	"github.com/GabrielNunesIT/gotya/schema"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Test_FullAssetSuite_GoGeneration tests Go code generation with the full YANG asset suite.
// This test loads all available YANG files from the assets directory and generates Go code,
// validating that the output is syntactically correct and contains expected code structures.
func Test_FullAssetSuite_GoGeneration(t *testing.T) {
	assetDir := filepath.Join("..", "assets")
	_, err := os.Stat(assetDir)
	if os.IsNotExist(err) {
		t.Skip("assets directory not found, skipping full suite test")
	}

	// Load all YANG modules from assets
	yangFiles, err := filepath.Glob(filepath.Join(assetDir, "*.yang"))
	require.NoError(t, err, "failed to glob YANG files")
	require.NotEmpty(t, yangFiles, "no YANG files found in assets directory")
	
	// Sort files for deterministic test execution
	sort.Strings(yangFiles)

	t.Logf("Found %d YANG files to process", len(yangFiles))

	// Parse all YANG files
	var astModules []*gotya.ASTModule
	var successfulParsing []string
	var failedParsing []string

	for _, yangFile := range yangFiles {
		moduleName := filepath.Base(yangFile)
		astMod, err := gotya.ParseFile(yangFile)
		if err != nil {
			failedParsing = append(failedParsing, fmt.Sprintf("%s: %v", moduleName, err))
			continue
		}
		if astMod.Keyword() == "submodule" {
			// Skip submodules, they're handled via include
			continue
		}
		astModules = append(astModules, astMod)
		successfulParsing = append(successfulParsing, moduleName)
	}

	if len(failedParsing) > 0 {
		t.Logf("Failed to parse %d modules:\n%s", len(failedParsing), strings.Join(failedParsing, "\n"))
	}
	require.NotEmpty(t, astModules, "no YANG modules parsed successfully")
	t.Logf("Successfully parsed %d modules", len(astModules))

	// Test various generator options
	testCases := []struct {
		name    string
		options *golang.Options
	}{
		{
			name:    "Basic generation",
			options: &golang.Options{PackageName: "device"},
		},
		{
			name: "With fakeroot",
			options: &golang.Options{
				PackageName:      "device",
				GenerateFakeroot: true,
				RootName:         "Root",
			},
		},
		{
			name: "With getters and setters",
			options: &golang.Options{
				PackageName:      "device",
				GenerateGetters:  true,
				GenerateSetters:  true,
				GenerateFakeroot: true,
			},
		},
		{
			name: "Skip deprecated and obsolete",
			options: &golang.Options{
				PackageName:     "device",
				SkipDeprecated:  true,
				SkipObsolete:    true,
				GenerateFakeroot: true,
			},
		},
		{
			name: "With annotations and methods",
			options: &golang.Options{
				PackageName:              "device",
				AddAnnotations:           true,
				GeneratePopulateDefault:  true,
				GenerateOrderedMaps:      true,
				GenerateFakeroot:         true,
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			gen := golang.New(tc.options)
			var buf bytes.Buffer

			// Test GenerateDevice with all modules
			err := gen.GenerateDevice(convertToSchemaModules(t, astModules, assetDir), &buf)
			require.NoError(t, err, "GenerateDevice failed")

			output := buf.String()
			require.NotEmpty(t, output, "GenerateDevice produced empty output")

			// Verify output can be formatted
			formatted, err := format.Source(buf.Bytes())
			require.NoError(t, err, "generated Go code is not syntactically valid")

			// Verify expected content
			assert.Contains(t, output, "package "+tc.options.PackageName)
			assert.Contains(t, output, "// Code generated by gotya")

			// Spot-check for struct definitions
			if tc.options.GenerateFakeroot {
				assert.Contains(t, output, "type "+tc.options.RootName+"Config struct", "missing root Config struct")
				assert.Contains(t, output, "type "+tc.options.RootName+"State struct", "missing root State struct")
			}

			t.Logf("Generated %d bytes of Go code (%d formatted)", len(output), len(formatted))
		})
	}
}

// Test_FullAssetSuite_ProtobufGeneration tests Protobuf code generation with the full YANG asset suite.
// This test generates Protobuf v3 definitions and validates syntax and structure.
func Test_FullAssetSuite_ProtobufGeneration(t *testing.T) {
	assetDir := filepath.Join("..", "assets")
	_, err := os.Stat(assetDir)
	if os.IsNotExist(err) {
		t.Skip("assets directory not found, skipping full suite test")
	}

	yangFiles, err := filepath.Glob(filepath.Join(assetDir, "*.yang"))
	require.NoError(t, err, "failed to glob YANG files")
	require.NotEmpty(t, yangFiles, "no YANG files found")
	
	// Sort files for deterministic test execution
	sort.Strings(yangFiles)

	// Parse YANG files
	var astModules []*gotya.ASTModule
	for _, yangFile := range yangFiles {
		astMod, err := gotya.ParseFile(yangFile)
		if err != nil {
			continue
		}
		if astMod.Keyword() == "submodule" {
			continue
		}
		astModules = append(astModules, astMod)
	}
	require.NotEmpty(t, astModules)

	testCases := []struct {
		name    string
		options *protobuf.Options
	}{
		{
			name:    "Basic generation",
			options: &protobuf.Options{PackageName: "ygot"},
		},
		{
			name: "With fakeroot",
			options: &protobuf.Options{
				PackageName:      "ygot",
				GenerateFakeroot: true,
			},
		},
		{
			name: "With CEL validation",
			options: &protobuf.Options{
				PackageName:          "ygot",
				GenerateFakeroot:     true,
				GenerateCELValidation: true,
			},
		},
		{
			name: "With populate defaults",
			options: &protobuf.Options{
				PackageName:             "ygot",
				GeneratePopulateDefault: true,
				GenerateFakeroot:        true,
			},
		},
		{
			name: "Skip deprecated and obsolete",
			options: &protobuf.Options{
				PackageName:      "ygot",
				SkipDeprecated:   true,
				SkipObsolete:     true,
				GenerateFakeroot: true,
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			gen := protobuf.New(tc.options)
			var buf bytes.Buffer

			err := gen.GenerateDevice(convertToSchemaModules(t, astModules, assetDir), &buf)
			require.NoError(t, err, "GenerateDevice failed for "+tc.name)

			output := buf.String()
			require.NotEmpty(t, output, "GenerateDevice produced empty output")

			// Verify protobuf structure
			assert.Contains(t, output, "syntax = \"proto3\";", "missing proto3 syntax declaration")
			assert.Contains(t, output, "package "+tc.options.PackageName, "missing package declaration")
			assert.Contains(t, output, "// Code generated by gotya")

			// Verify message definitions
			if tc.options.GenerateFakeroot {
				assert.Contains(t, output, "message "+tc.options.RootName+" {", "missing root message")
			}

			// Verify no duplicate field numbers within messages
			verifyProtobufFieldNumbers(t, output)

			t.Logf("Generated %d bytes of Protobuf code", len(output))
		})
	}
}

// Test_FullAssetSuite_ProtobufWithCEL tests Protobuf code generation with CEL validation constraints.
// CEL (Common Expression Language) validation is used to emit bufbuild/protovalidate constraints
// for YANG types with restrictions (range, length, pattern, etc.).
func Test_FullAssetSuite_ProtobufWithCEL(t *testing.T) {
	assetDir := filepath.Join("..", "assets")
	_, err := os.Stat(assetDir)
	if os.IsNotExist(err) {
		t.Skip("assets directory not found, skipping CEL test")
	}

	yangFiles, err := filepath.Glob(filepath.Join(assetDir, "*.yang"))
	require.NoError(t, err)
	require.NotEmpty(t, yangFiles)

	// Sort files for deterministic test execution
	sort.Strings(yangFiles)

	var astModules []*gotya.ASTModule
	for _, yangFile := range yangFiles {
		astMod, err := gotya.ParseFile(yangFile)
		if err != nil || astMod.Keyword() == "submodule" {
			continue
		}
		astModules = append(astModules, astMod)
	}
	require.NotEmpty(t, astModules, "no YANG modules parsed successfully")

	schemaModules := convertToSchemaModules(t, astModules, assetDir)
	require.NotEmpty(t, schemaModules, "no schema modules compiled")

	// Test Protobuf generation with CEL validation enabled
	opts := &protobuf.Options{
		PackageName:           "ygot_cel",
		RootName:              "Device",
		GenerateFakeroot:      true,
		GenerateCELValidation: true,
	}

	gen := protobuf.New(opts)
	var buf bytes.Buffer
	err = gen.GenerateDevice(schemaModules, &buf)
	require.NoError(t, err, "Protobuf+CEL generation must not fail with asset suite")

	output := buf.String()
	require.NotEmpty(t, output, "GenerateDevice with CEL must produce output")

	// Verify protobuf structure with CEL
	assert.Contains(t, output, "syntax = \"proto3\";")
	assert.Contains(t, output, "package "+opts.PackageName)
	assert.Contains(t, output, "// Code generated by gotya")

	// Verify CEL import is present when GenerateCELValidation is enabled
	assert.Contains(t, output, "import \"buf/validate/validate.proto\";",
		"CEL validation requires bufbuild/protovalidate import")

	// Verify field numbers are valid
	verifyProtobufFieldNumbers(t, output)

	t.Logf("Generated %d bytes of Protobuf+CEL code", len(output))
}

// Test_FullAssetSuite_ProtobufCELVsNoCEL tests that CEL validation option produces different output.
// With CEL enabled, leaf/leaflist fields with constraints should have validate options.
func Test_FullAssetSuite_ProtobufCELVsNoCEL(t *testing.T) {
	assetDir := filepath.Join("..", "assets")
	_, err := os.Stat(assetDir)
	if os.IsNotExist(err) {
		t.Skip("assets directory not found")
	}

	yangFiles, err := filepath.Glob(filepath.Join(assetDir, "*.yang"))
	require.NoError(t, err)
	require.NotEmpty(t, yangFiles)

	// Sort for determinism
	sort.Strings(yangFiles)

	var astModules []*gotya.ASTModule
	for _, yangFile := range yangFiles {
		astMod, err := gotya.ParseFile(yangFile)
		if err != nil || astMod.Keyword() == "submodule" {
			continue
		}
		astModules = append(astModules, astMod)
	}
	require.NotEmpty(t, astModules)

	schemaModules := convertToSchemaModules(t, astModules, assetDir)
	require.NotEmpty(t, schemaModules)

	// Generate without CEL
	noCELOpts := &protobuf.Options{
		PackageName:      "ygot_no_cel",
		GenerateFakeroot: true,
	}
	noCELGen := protobuf.New(noCELOpts)
	var noCELBuf bytes.Buffer
	err = noCELGen.GenerateDevice(schemaModules, &noCELBuf)
	require.NoError(t, err)

	noCELOutput := noCELBuf.String()

	// Generate with CEL
	celOpts := &protobuf.Options{
		PackageName:           "ygot_with_cel",
		GenerateFakeroot:      true,
		GenerateCELValidation: true,
	}
	celGen := protobuf.New(celOpts)
	var celBuf bytes.Buffer
	err = celGen.GenerateDevice(schemaModules, &celBuf)
	require.NoError(t, err)

	celOutput := celBuf.String()

	// Verify CEL output has the validation import
	assert.Contains(t, celOutput, "import \"buf/validate/validate.proto\";",
		"CEL output must import buf/validate/validate.proto")
	assert.NotContains(t, noCELOutput, "import \"buf/validate/validate.proto\";",
		"non-CEL output must not import buf/validate/validate.proto")

	// Verify lengths are different (CEL has validation constraints)
	require.NotEqual(t, len(noCELOutput), len(celOutput),
		"CEL and non-CEL outputs must differ in size due to validation constraints")

	t.Logf("Without CEL: %d bytes; With CEL: %d bytes (delta: %d)",
		len(noCELOutput), len(celOutput), len(celOutput)-len(noCELOutput))
}

// Test_FullAssetSuite_ConsistentOutput validates that generation is deterministic.
// Regenerating the same modules should produce identical output.
func Test_FullAssetSuite_ConsistentOutput(t *testing.T) {
	assetDir := filepath.Join("..", "assets")
	_, err := os.Stat(assetDir)
	if os.IsNotExist(err) {
		t.Skip("assets directory not found")
	}

	yangFiles, err := filepath.Glob(filepath.Join(assetDir, "*.yang"))
	require.NoError(t, err)

	// Sort files for deterministic test execution
	sort.Strings(yangFiles)

	var astModules []*gotya.ASTModule
	for _, yangFile := range yangFiles {
		astMod, err := gotya.ParseFile(yangFile)
		if err != nil || astMod.Keyword() == "submodule" {
			continue
		}
		astModules = append(astModules, astMod)
	}
	require.NotEmpty(t, astModules)

	// Generate Go code twice
	opts := &golang.Options{
		PackageName:      "device",
		GenerateFakeroot: true,
	}

	gen1 := golang.New(opts)
	var buf1 bytes.Buffer
	err = gen1.GenerateDevice(convertToSchemaModules(t, astModules, assetDir), &buf1)
	require.NoError(t, err)

	gen2 := golang.New(opts)
	var buf2 bytes.Buffer
	err = gen2.GenerateDevice(convertToSchemaModules(t, astModules, assetDir), &buf2)
	require.NoError(t, err)

	// Compare outputs
	assert.Equal(t, buf1.String(), buf2.String(), "generation is not deterministic")
	t.Log("Generation output is deterministic")
}

// Test_FullAssetSuite_NoNilPointerDereferences validates robustness against edge cases.
func Test_FullAssetSuite_NoNilPointerDereferences(t *testing.T) {
	assetDir := filepath.Join("..", "assets")
	_, err := os.Stat(assetDir)
	if os.IsNotExist(err) {
		t.Skip("assets directory not found")
	}

	yangFiles, err := filepath.Glob(filepath.Join(assetDir, "*.yang"))
	require.NoError(t, err)
	require.NotEmpty(t, yangFiles)

	// Sort files for deterministic test execution
	sort.Strings(yangFiles)

	var astModules []*gotya.ASTModule
	for _, yangFile := range yangFiles {
		astMod, err := gotya.ParseFile(yangFile)
		if err != nil || astMod.Keyword() == "submodule" {
			continue
		}
		astModules = append(astModules, astMod)
	}
	require.NotEmpty(t, astModules)

	schemaModules := convertToSchemaModules(t, astModules, assetDir)

	// Test Go generator with nil-prone options
	goOpts := &golang.Options{
		PackageName:      "test",
		GenerateFakeroot: true,
		AddAnnotations:   true,
		SkipDeprecated:   true,
		SkipObsolete:     true,
	}

	goGen := golang.New(goOpts)
	var goBuf bytes.Buffer
	err = goGen.GenerateDevice(schemaModules, &goBuf)
	require.NoError(t, err, "Go generator panicked or failed with the asset suite")

	// Test Protobuf generator
	pbOpts := &protobuf.Options{
		PackageName:          "test_pb",
		GenerateFakeroot:     true,
		GenerateCELValidation: true,
	}

	pbGen := protobuf.New(pbOpts)
	var pbBuf bytes.Buffer
	err = pbGen.GenerateDevice(schemaModules, &pbBuf)
	require.NoError(t, err, "Protobuf generator panicked or failed with the asset suite")

	t.Logf("Both generators handled %.0f modules without nil pointer issues", float64(len(schemaModules)))
}

// Helper functions

// assetLoader loads YANG modules from an asset directory with dependency resolution
type assetLoader struct {
	dir         string
	astCache    map[string]*ast.Module
	schemaCache map[string]*schema.Module
}

// newAssetLoader creates a new asset loader for a given directory
func newAssetLoader(dir string) *assetLoader {
	return &assetLoader{
		dir:         dir,
		astCache:    make(map[string]*ast.Module),
		schemaCache: make(map[string]*schema.Module),
	}
}

// Load compiles a module from the asset directory with dependency resolution
func (l *assetLoader) Load(name string) (*schema.Module, error) {
	if m, ok := l.schemaCache[name]; ok {
		return m, nil
	}

	astMod, err := l.LoadAST(name)
	if err != nil {
		return nil, err
	}

	comp := compiler.New(&compiler.Options{Loader: l})
	schemaMod, err := comp.Compile(astMod)

	if schemaMod != nil && err == nil {
		l.schemaCache[name] = schemaMod
		if schemaMod.Name != name && schemaMod.Name != "" {
			l.schemaCache[schemaMod.Name] = schemaMod
		}
	}

	if err != nil {
		return schemaMod, err
	}

	return schemaMod, nil
}

// LoadAST loads and parses a YANG module from the asset directory
func (l *assetLoader) LoadAST(name string) (*ast.Module, error) {
	if m, ok := l.astCache[name]; ok {
		return m, nil
	}

	files, err := os.ReadDir(l.dir)
	if err != nil {
		return nil, err
	}

	var targetPath string
	for _, f := range files {
		if strings.HasPrefix(f.Name(), name+".yang") || strings.HasPrefix(f.Name(), name+"@") {
			targetPath = filepath.Join(l.dir, f.Name())
			break
		}
	}

	if targetPath == "" {
		return nil, fmt.Errorf("module %s not found in %s", name, l.dir)
	}

	content, err := os.ReadFile(targetPath)
	if err != nil {
		return nil, err
	}

	lex := lexer.New(string(content))
	p := parser.New(lex)
	astMod := p.ParseModule()
	if astMod == nil {
		return nil, fmt.Errorf("failed to parse module AST for %s", name)
	}

	l.astCache[name] = astMod
	if astMod.Argument() != name {
		l.astCache[astMod.Argument()] = astMod
	}

	return astMod, nil
}

// Helper functions

func convertToSchemaModules(t *testing.T, astModules []*gotya.ASTModule, assetDir string) []*schema.Module {
	// Create a proper loader that can resolve cross-module dependencies from the asset directory
	loader := newAssetLoader(assetDir)

	var schemaModules []*schema.Module
	for _, astMod := range astModules {
		modName := astMod.Name()
		schemaMod, err := loader.Load(modName)
		if err != nil {
			t.Logf("Warning: failed to compile module %s: %v (will skip)", modName, err)
			continue
		}
		schemaModules = append(schemaModules, schemaMod)
	}
	return schemaModules
}

// verifyProtobufFieldNumbers checks that protobuf field numbers are sequential and non-duplicated within each message.
func verifyProtobufFieldNumbers(t *testing.T, proto string) {
	lines := strings.Split(proto, "\n")
	var currentMessage string
	var fieldNumbers map[string]map[int]bool = make(map[string]map[int]bool)

	for _, line := range lines {
		line = strings.TrimSpace(line)

		// Track current message
		if strings.HasPrefix(line, "message ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				currentMessage = parts[1]
				fieldNumbers[currentMessage] = make(map[int]bool)
			}
			continue
		}

		// Extract field number
		if currentMessage != "" && strings.Contains(line, " = ") {
			// Parse field definition: "type field_name = number [options];"
			parts := strings.Split(line, " = ")
			if len(parts) >= 2 {
				numPart := strings.FieldsFunc(parts[1], func(r rune) bool { return r == ';' || r == '[' || r == ' ' })
				if len(numPart) > 0 {
					var fieldNum int
					_, _ = fmt.Sscanf(numPart[0], "%d", &fieldNum)
					if fieldNum > 0 {
						if fieldNumbers[currentMessage][fieldNum] {
							t.Errorf("Duplicate field number %d in message %s", fieldNum, currentMessage)
						}
						fieldNumbers[currentMessage][fieldNum] = true
					}
				}
			}
		}

		// End of message
		if line == "}" {
			currentMessage = ""
		}
	}

	// Report findings
	for msg, nums := range fieldNumbers {
		if len(nums) > 0 {
			t.Logf("Message %s: %d fields with numbers %d to %d", msg, len(nums), findMin(nums), findMax(nums))
		}
	}
}

func findMin(m map[int]bool) int {
	min := int(^uint(0) >> 1)
	for k := range m {
		if k < min {
			min = k
		}
	}
	return min
}

func findMax(m map[int]bool) int {
	max := 0
	for k := range m {
		if k > max {
			max = k
		}
	}
	return max
}
