// Package protobuf provides the generator implementation for emitting Protobuf v3 files.
package protobuf

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/gotya/gotya/domain/schema"
	"github.com/gotya/gotya/usecases/generator"
)

// ProtoGenerator implements the generator.Generator interface for Protobuf map generation.
type ProtoGenerator struct {
	PackageName string
}

// New creates a new ProtoGenerator instance.
func New(pkgName string) generator.Generator {
	if pkgName == "" {
		pkgName = "yproto" // default
	}
	return &ProtoGenerator{
		PackageName: pkgName,
	}
}

// Generate writes Protobuf v3 source code for the parsed module.
func (g *ProtoGenerator) Generate(mod *schema.Module, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Code generated by gotya. DO NOT EDIT.\nsyntax = \"proto3\";\npackage %s;\n\n", g.PackageName); err != nil {
		return fmt.Errorf("failed to write package header: %w", err)
	}

	visited := make(map[string]bool)
	for _, node := range mod.Nodes {
		if err := g.generateNode(node, w, visited); err != nil {
			return err
		}
	}
	return nil
}

// GenerateDevice takes a list of validated YANG modules, aggregates them into a single Device root struct,
// encapsulating their configurations under Module-specific messages.
func (g *ProtoGenerator) GenerateDevice(modules []*schema.Module, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Code generated by gotya. DO NOT EDIT.\nsyntax = \"proto3\";\npackage %s;\n\n", g.PackageName); err != nil {
		return fmt.Errorf("failed to write package header: %w", err)
	}

	visited := make(map[string]bool)
	var allTopLevelNodes []schema.Node

	if _, err := fmt.Fprintf(w, "message Device {\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	fieldIndex := 1
	for _, mod := range modules {
		if len(mod.Nodes) == 0 {
			continue // skip empty modules
		}

		modMsgName := toCamelCaseTitle(mod.Name)
		fieldName := convertToSnakeCase(mod.Name)
		if _, err := fmt.Fprintf(w, "\t%s %s = %d;\n", modMsgName, fieldName, fieldIndex); err != nil {
			return err
		}
		fieldIndex++
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	for _, mod := range modules {
		if len(mod.Nodes) == 0 {
			continue
		}

		modMsgName := toCamelCaseTitle(mod.Name)
		if visited[modMsgName] {
			continue
		}
		visited[modMsgName] = true

		if _, err := fmt.Fprintf(w, "message %s {\n", modMsgName); err != nil {
			return fmt.Errorf("write err: %w", err)
		}

		if err := g.generateEnumBlocks(mod.Nodes, w); err != nil {
			return err
		}

		modFieldIndex := 1
		for _, childName := range getSortedChildNames(mod.Nodes) {
			child := mod.Nodes[childName]
			allTopLevelNodes = append(allTopLevelNodes, child) // collect for deep generations
			if err := g.generateField(child, w, &modFieldIndex); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
	}

	for _, node := range allTopLevelNodes {
		if err := g.generateNode(node, w, visited); err != nil {
			return err
		}
		if choice, ok := node.(*schema.Choice); ok {
			for _, caseName := range getSortedChildNames(choice.Children) {
				caseNode := choice.Children[caseName]
				if c, ok := caseNode.(*schema.Case); ok {
					if err := g.generateCaseMessage(c, w, visited); err != nil {
						return err
					}
				}
			}
		}
	}

	return nil
}

func (g *ProtoGenerator) generateNode(node schema.Node, w io.Writer, visited map[string]bool) error {
	switch n := node.(type) {
	case *schema.Container:
		return g.generateMessage(n.Name(), n.Children, w, visited)
	case *schema.List:
		return g.generateMessage(n.Name(), n.Children, w, visited)
	}
	return nil
}

func (g *ProtoGenerator) generateMessage(name string, children map[string]schema.Node, w io.Writer, visited map[string]bool) error {
	msgName := toCamelCaseTitle(name)
	if visited[msgName] {
		return nil
	}
	visited[msgName] = true

	if _, err := fmt.Fprintf(w, "message %s {\n", msgName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	if err := g.generateEnumBlocks(children, w); err != nil {
		return err
	}

	fieldIndex := 1
	for _, childName := range getSortedChildNames(children) {
		child := children[childName]
		if err := g.generateField(child, w, &fieldIndex); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// Recurse for nested messages
	for _, childName := range getSortedChildNames(children) {
		child := children[childName]
		if err := g.generateNode(child, w, visited); err != nil {
			return err
		}
		// Also handle nested cases if any
		if choice, ok := child.(*schema.Choice); ok {
			for _, caseName := range getSortedChildNames(choice.Children) {
				caseNode := choice.Children[caseName]
				if c, ok := caseNode.(*schema.Case); ok {
					if err := g.generateCaseMessage(c, w, visited); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

func (g *ProtoGenerator) generateCaseMessage(n *schema.Case, w io.Writer, visited map[string]bool) error {
	// A case needs its own message if it contains multiple items or nested structures to be serialized as oneof payload
	msgName := toCamelCaseTitle(n.Name()) + "Case"
	if visited[msgName] {
		return nil
	}
	visited[msgName] = true

	if _, err := fmt.Fprintf(w, "message %s {\n", msgName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	fieldIndex := 1
	for _, childName := range getSortedChildNames(n.Children) {
		child := n.Children[childName]
		if err := g.generateField(child, w, &fieldIndex); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	for _, childName := range getSortedChildNames(n.Children) {
		child := n.Children[childName]
		if err := g.generateNode(child, w, visited); err != nil {
			return err
		}
	}
	return nil
}

func (g *ProtoGenerator) generateField(node schema.Node, w io.Writer, fieldIndex *int) error {
	fieldName := convertToSnakeCase(node.Name())
	var protoType string

	switch n := node.(type) {
	case *schema.Leaf:
		if len(n.Type.Length) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: length %v\n", n.Type.Length); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if len(n.Type.Range) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: range %v\n", n.Type.Range); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if len(n.Type.Pattern) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: pattern %v\n", n.Type.Pattern); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if n.Type.Name == "enumeration" && len(n.Type.Enums) > 0 {
			protoType = toCamelCaseTitle(n.Name())
		} else {
			protoType = mapYANGTypeToProto(n.Type.Name)
		}
		if _, err := fmt.Fprintf(w, "\t%s %s = %d;\n", protoType, fieldName, *fieldIndex); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.LeafList:
		if len(n.Type.Length) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: length %v\n", n.Type.Length); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if len(n.Type.Range) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: range %v\n", n.Type.Range); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if len(n.Type.Pattern) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: pattern %v\n", n.Type.Pattern); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		protoType = "repeated " + mapYANGTypeToProto(n.Type.Name)
		if _, err := fmt.Fprintf(w, "\t%s %s = %d;\n", protoType, fieldName, *fieldIndex); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.Container:
		protoType = toCamelCaseTitle(n.Name())
		if _, err := fmt.Fprintf(w, "\t%s %s = %d;\n", protoType, fieldName, *fieldIndex); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.List:
		protoType = "repeated " + toCamelCaseTitle(n.Name())
		if _, err := fmt.Fprintf(w, "\t%s %s = %d;\n", protoType, fieldName, *fieldIndex); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.Choice:
		if _, err := fmt.Fprintf(w, "\toneof %s {\n", fieldName); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		for _, caseName := range getSortedChildNames(n.Children) {
			if _, ok := n.Children[caseName].(*schema.Case); !ok {
				continue
			}
			caseFieldName := convertToSnakeCase(caseName)
			caseMsgName := toCamelCaseTitle(caseName) + "Case"
			if _, err := fmt.Fprintf(w, "\t\t%s %s = %d;\n", caseMsgName, caseFieldName, *fieldIndex); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			*fieldIndex++
		}
		if _, err := fmt.Fprintf(w, "\t}\n"); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
	}

	return nil
}

func (g *ProtoGenerator) generateEnumBlocks(children map[string]schema.Node, w io.Writer) error {
	for _, childName := range getSortedChildNames(children) {
		child := children[childName]
		if leaf, ok := child.(*schema.Leaf); ok && leaf.Type.Name == "enumeration" && len(leaf.Type.Enums) > 0 {
			enumName := toCamelCaseTitle(leaf.Name())
			if _, err := fmt.Fprintf(w, "\tenum %s {\n", enumName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			for i, enumVal := range leaf.Type.Enums {
				enumValName := fmt.Sprintf("%s_%s", strings.ToUpper(convertToSnakeCase(enumName)), strings.ToUpper(convertToSnakeCase(enumVal)))
				if _, err := fmt.Fprintf(w, "\t\t%s = %d;\n", enumValName, i); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
			if _, err := fmt.Fprintf(w, "\t}\n"); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	return nil
}

func toCamelCaseTitle(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func convertToSnakeCase(s string) string {
	return strings.ReplaceAll(strings.ToLower(s), "-", "_")
}

func mapYANGTypeToProto(yangType string) string {
	switch yangType {
	case "int8", "int16", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "uint8", "uint16", "uint32":
		return "uint32"
	case "uint64":
		return "uint64"
	case "boolean":
		return "bool"
	case "decimal64":
		return "double"
	case "empty":
		return "bool"
	case "binary":
		return "bytes"
	default:
		return "string"
	}
}

func getSortedChildNames(children map[string]schema.Node) []string {
	names := make([]string, 0, len(children))
	for name := range children {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
