// Package golang provides the generator implementation for emitting Go source files.
package golang

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/gotya/gotya/domain/schema"
	"github.com/gotya/gotya/usecases/generator"
)

// GoGenerator implements the generator.Generator interface for Go struct generation.
type GoGenerator struct {
	PackageName string
}

// New creates a new GoGenerator instance.
func New(pkgName string) generator.Generator {
	if pkgName == "" {
		pkgName = "ygot" // default
	}
	return &GoGenerator{
		PackageName: pkgName,
	}
}

// Generate writes Go source code for the parsed module to the provided writer.
func (g *GoGenerator) Generate(mod *schema.Module, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Code generated by gotya. DO NOT EDIT.\npackage %s\n\n", g.PackageName); err != nil {
		return fmt.Errorf("failed to write package header: %w", err)
	}

	visited := make(map[string]bool)
	prefix := toCamelCaseTitle(mod.Name)
	for _, node := range mod.Nodes {
		if err := g.generateNode(node, w, visited, prefix, "", mod.Namespace, false); err != nil {
			return err
		}
	}
	return nil
}

// hasValidNodes checks if a node contains any data that should be exported taking into account its config flag.
func (g *GoGenerator) hasValidNodes(node schema.Node, configOnly bool) bool {
	if configOnly && !node.Config() {
		return false
	}

	switch n := node.(type) {
	case *schema.Leaf, *schema.LeafList, *schema.AnyXML, *schema.AnyData:
		return true
	case *schema.Container:
		for _, child := range getFlatDataNodes(n.Children) {
			if g.hasValidNodes(child, configOnly) {
				return true
			}
		}
	case *schema.List:
		for _, child := range getFlatDataNodes(n.Children) {
			if g.hasValidNodes(child, configOnly) {
				return true
			}
		}
	}
	return false
}

// GenerateDevice takes a list of validated YANG modules, aggregates them into a single root struct,
// encapsulating their configurations under Module-specific structs. It emits both Config and State representations.
func (g *GoGenerator) GenerateDevice(modules []*schema.Module, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Code generated by gotya. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"encoding/json\"\n\t\"encoding/xml\"\n\t\"fmt\"\n\t\"regexp\"\n\t\"unicode/utf8\"\n)\n\n", g.PackageName); err != nil {
		return fmt.Errorf("failed to write package header: %w", err)
	}

	// visited tracks generated type names across both Config and State passes
	// to prevent duplicate struct / union-type declarations in the same file.
	visited := make(map[string]bool)

	for _, treeType := range []string{"Config", "State"} {
		configOnly := (treeType == "Config")

		if _, err := fmt.Fprintf(w, "// Device%s represents the aggregated YANG configuration.\n", treeType); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		if _, err := fmt.Fprintf(w, "type Device%s struct {\n", treeType); err != nil {
			return fmt.Errorf("write err: %w", err)
		}

		for _, mod := range modules {
			hasValid := false
			for _, node := range mod.Nodes {
				if g.hasValidNodes(node, configOnly) {
					hasValid = true
					break
				}
			}
			if !hasValid {
				continue // skip modules without valid fields
			}

			modStructName := toCamelCaseTitle(mod.Name) + treeType
			modFieldName := toCamelCaseTitle(mod.Name)
			xmlTag := fmt.Sprintf(" xml:\"%s,omitempty\"", mod.Name)
			if mod.Namespace != "" {
				xmlTag = fmt.Sprintf(" xml:\"%s %s,omitempty\"", mod.Namespace, mod.Name)
			}
			if _, err := fmt.Fprintf(w, "\t%s *%s `json:\"%s,omitempty\"%s`\n", modFieldName, modStructName, mod.Name, xmlTag); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
			return fmt.Errorf("write err: %w", err)
		}

		// Validate method for root Device
		if _, err := fmt.Fprintf(w, "// Validate verifies the constraints of Device%s.\nfunc (s *Device%s) Validate() error {\n", treeType, treeType); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		for _, mod := range modules {
			hasValid := false
			for _, node := range mod.Nodes {
				if g.hasValidNodes(node, configOnly) {
					hasValid = true
					break
				}
			}
			if !hasValid {
				continue
			}
			modFieldName := toCamelCaseTitle(mod.Name)
			if _, err := fmt.Fprintf(w, "\tif s.%s != nil {\n\t\tif err := s.%s.Validate(); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n", modFieldName, modFieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if _, err := fmt.Fprintf(w, "\treturn nil\n}\n\n"); err != nil {
			return fmt.Errorf("write err: %w", err)
		}

		// Now generate each Module Struct
		for _, mod := range modules {
			hasValid := false
			for _, node := range mod.Nodes {
				if g.hasValidNodes(node, configOnly) {
					hasValid = true
					break
				}
			}
			if !hasValid {
				continue
			}

			modStructName := toCamelCaseTitle(mod.Name) + treeType
			if visited[modStructName] {
				continue
			}
			visited[modStructName] = true

			if _, err := fmt.Fprintf(w, "// %s represents the YANG module %s.\n", modStructName, mod.Name); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			if _, err := fmt.Fprintf(w, "type %s struct {\n", modStructName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}

			var modTopNodes []schema.Node
			for _, name := range getOrderedChildNames(mod.Nodes) {
				child := mod.Nodes[name]
				if !g.hasValidNodes(child, configOnly) {
					continue
				}
				modTopNodes = append(modTopNodes, child)
			}

			prefix := toCamelCaseTitle(mod.Name)
			for _, node := range modTopNodes {
				// Handle 'Validate' collision when generating the struct fields directly
				fieldName := toCamelCaseTitle(node.Name())
				if fieldName == "Validate" {
					fieldName = "ValidateField"
				}
				goType := "*string" // Default placeholder
				switch n := node.(type) {
				case *schema.Leaf:
					goType = mapYANGTypeToGo(n.Type.Name)
				case *schema.LeafList:
					goType = "[]" + mapYANGTypeToGo(n.Type.Name)
				case *schema.Container:
					goType = "*" + prefix + toCamelCaseTitle(n.Name()) + treeType
				case *schema.List:
					goType = "map[string]*" + prefix + toCamelCaseTitle(n.Name()) + treeType
				}
				xmlTag := fmt.Sprintf(" xml:\"%s,omitempty\"", node.Name())
				if mod.Namespace != "" {
					xmlTag = fmt.Sprintf(" xml:\"%s %s,omitempty\"", mod.Namespace, node.Name())
				}
				if _, err := fmt.Fprintf(w, "\t%s %s `json:\"%s,omitempty\"%s`\n", fieldName, goType, node.Name(), xmlTag); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
			if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
				return fmt.Errorf("write err: %w", err)
			}

			if err := g.generateValidationChecks(modStructName, modTopNodes, w); err != nil {
				return err
			}

			for _, node := range modTopNodes {
				if err := g.generateNode(node, w, visited, prefix, treeType, mod.Namespace, configOnly); err != nil {
					return err
				}
			}
		}
	}

	return nil
}

func (g *GoGenerator) generateNode(node schema.Node, w io.Writer, visited map[string]bool, prefix, suffix, namespace string, configOnly bool) error {
	switch n := node.(type) {
	case *schema.Container:
		return g.generateStruct(n.Name(), n.Children, "container", w, visited, prefix, suffix, namespace, configOnly)
	case *schema.List:
		return g.generateStruct(n.Name()+"Entry", n.Children, "list", w, visited, prefix, suffix, namespace, configOnly)
	case *schema.Leaf:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			ut := unionGoTypeName(prefix, n.Name())
			if !visited[ut] {
				visited[ut] = true
				if err := g.generateUnionStruct(ut, n.Type.Members, w); err != nil {
					return err
				}
			}
		}
	case *schema.LeafList:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			ut := unionGoTypeName(prefix, n.Name())
			if !visited[ut] {
				visited[ut] = true
				if err := g.generateUnionStruct(ut, n.Type.Members, w); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (g *GoGenerator) generateStruct(name string, children map[string]schema.Node, kind string, w io.Writer, visited map[string]bool, prefix, suffix, namespace string, configOnly bool) error {
	structName := prefix + toCamelCaseTitle(name) + suffix
	if visited[structName] {
		return nil
	}
	visited[structName] = true

	flatNodes := getFlatDataNodes(children)
	var validFlatNodes []schema.Node
	for _, child := range flatNodes {
		if g.hasValidNodes(child, configOnly) {
			validFlatNodes = append(validFlatNodes, child)
		}
	}

	if len(validFlatNodes) == 0 {
		return nil
	}

	if _, err := fmt.Fprintf(w, "// %s represents the YANG %s %s.\n", structName, kind, name); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	if _, err := fmt.Fprintf(w, "type %s struct {\n", structName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	for _, child := range validFlatNodes {
		if err := g.generateField(child, w, prefix, suffix, namespace); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	if err := g.generateValidationChecks(structName, validFlatNodes, w); err != nil {
		return err
	}

	// Recurse for nested structs
	for _, child := range validFlatNodes {
		if err := g.generateNode(child, w, visited, prefix, suffix, namespace, configOnly); err != nil {
			return err
		}
	}
	return nil
}

func (g *GoGenerator) generateField(node schema.Node, w io.Writer, prefix, suffix, namespace string) error {
	fieldName := toCamelCaseTitle(node.Name())
	if fieldName == "Validate" {
		fieldName = "ValidateField"
	}
	goType := "*string" // Default placeholder

	switch n := node.(type) {
	case *schema.Leaf:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			goType = "*" + unionGoTypeName(prefix, n.Name())
		} else {
			goType = mapYANGTypeToGo(n.Type.Name)
		}
	case *schema.LeafList:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			goType = "[]" + unionGoTypeName(prefix, n.Name())
		} else {
			goType = "[]" + mapYANGTypeToGo(n.Type.Name)
		}
	case *schema.Container:
		goType = "*" + prefix + toCamelCaseTitle(n.Name()) + suffix
	case *schema.List:
		goType = "[]*" + prefix + toCamelCaseTitle(n.Name()) + "Entry" + suffix
	}

	xmlTag := fmt.Sprintf(" xml:\"%s,omitempty\"", node.Name())
	if namespace != "" {
		xmlTag = fmt.Sprintf(" xml:\"%s %s,omitempty\"", namespace, node.Name())
	}
	if _, err := fmt.Fprintf(w, "\t%s %s `json:\"%s,omitempty\"%s`\n", fieldName, goType, node.Name(), xmlTag); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	return nil
}

func toCamelCaseTitle(s string) string {
	s = strings.ReplaceAll(s, ".", "_")
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func mapYANGTypeToGo(yangType string) string {
	switch yangType {
	case "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64":
		return "*" + yangType
	case "boolean":
		return "*bool"
	case "decimal64":
		return "*float64"
	case "empty":
		return "*bool"
	case "binary":
		return "[]byte"
	default:
		return "*string"
	}
}

func (g *GoGenerator) generateValidationChecks(structName string, flatNodes []schema.Node, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Validate verifies the constraints of %s.\n", structName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	if _, err := fmt.Fprintf(w, "func (s *%s) Validate() error {\n", structName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	for _, node := range flatNodes {
		fieldName := toCamelCaseTitle(node.Name())
		if (strings.HasSuffix(structName, "Config") || strings.HasSuffix(structName, "State")) && fieldName == "Validate" {
			fieldName = "ValidateField"
		}
		// In case any internal field is natively named Validate, we handle it during field generation
		if fieldName == "Validate" {
			fieldName = "ValidateField"
		}

		switch n := node.(type) {
		case *schema.Container:
			if _, err := fmt.Fprintf(w, "\tif s.%s != nil {\n\t\tif err := s.%s.Validate(); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n", fieldName, fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		case *schema.List:
			if _, err := fmt.Fprintf(w, "\tfor _, item := range s.%s {\n\t\tif item != nil {\n\t\t\tif err := item.Validate(); err != nil {\n\t\t\t\treturn err\n\t\t\t}\n\t\t}\n\t}\n", fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		case *schema.Leaf:
			if err := g.writeValidationRule(w, fieldName, "s."+fieldName, n.Type); err != nil {
				return err
			}
		case *schema.LeafList:
			if len(n.Type.Length) > 0 || len(n.Type.Range) > 0 || len(n.Type.Pattern) > 0 {
				if _, err := fmt.Fprintf(w, "\tfor _, item := range s.%s {\n", fieldName); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
				if err := g.writeValidationRule(w, fieldName, "item", n.Type); err != nil {
					return err
				}
				if _, err := fmt.Fprintf(w, "\t}\n"); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
		}
	}

	if _, err := fmt.Fprintf(w, "\treturn nil\n}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	return nil
}

// getOrderedChildNames returns the names of children sorted by their schema definition order.
func getOrderedChildNames(children map[string]schema.Node) []string {
	type nameOrder struct {
		name  string
		order int
	}
	list := make([]nameOrder, 0, len(children))
	for name, node := range children {
		list = append(list, nameOrder{
			name:  name,
			order: node.GetBase().Order,
		})
	}
	sort.Slice(list, func(i, j int) bool {
		return list[i].order < list[j].order
	})

	names := make([]string, len(list))
	for i, item := range list {
		names[i] = item.name
	}
	return names
}

// getFlatDataNodes recurses into Choice and Case nodes to extract the actual
// data tree children that participate in JSON/XML representations natively.
func getFlatDataNodes(nodes map[string]schema.Node) []schema.Node {
	var result []schema.Node
	seen := make(map[string]bool)

	var walk func(ns map[string]schema.Node)
	walk = func(ns map[string]schema.Node) {
		for _, name := range getOrderedChildNames(ns) {
			node := ns[name]
			switch n := node.(type) {
			case *schema.Choice:
				for _, caseName := range getOrderedChildNames(n.Children) {
					caseNode := n.Children[caseName]
					walk(caseNode.GetChildren())
				}
			case *schema.Case:
				walk(n.Children)
			default:
				if !seen[node.Name()] {
					seen[node.Name()] = true
					result = append(result, node)
				}
			}
		}
	}
	walk(nodes)
	return result
}


// unionGoTypeName builds a unique Go type name for a union leaf.
func unionGoTypeName(prefix, leafName string) string {
	return prefix + toCamelCaseTitle(leafName) + "Union"
}

// generateUnionStruct emits a union wrapper struct with one optional field per
// member type (in YANG declaration order) and the corresponding UnmarshalJSON /
// MarshalJSON methods that enforce RFC 7950 §7.4 ordered matching.
func (g *GoGenerator) generateUnionStruct(typeName string, members []schema.TypeDefinition, w io.Writer) error {
	// Build per-member field info: field name, Go type, unmarshal snippet.
	type memberInfo struct {
		fieldName string
		goType    string
		ptrType   bool   // true when the Go type is a pointer (*T)
		baseType  string // T without the leading *
	}
	seen := make(map[string]int)
	infos := make([]memberInfo, 0, len(members))
	for _, m := range members {
		goType := mapYANGTypeToGo(m.Name)
		// Derive a unique field name from the YANG type name.
		// Strip any module prefix (e.g. "bbf-qos-t:traffic-class-id" → "traffic-class-id")
		localName := m.Name
		if idx := strings.LastIndex(localName, ":"); idx >= 0 {
			localName = localName[idx+1:]
		}
		base := toCamelCaseTitle(localName)
		if _, exists := seen[base]; exists {
			seen[base]++
			base = fmt.Sprintf("%s%d", base, seen[base])
		} else {
			seen[base] = 0
		}
		isPtr := strings.HasPrefix(goType, "*")
		baseType := strings.TrimPrefix(goType, "*")
		infos = append(infos, memberInfo{
			fieldName: base,
			goType:    goType,
			ptrType:   isPtr,
			baseType:  baseType,
		})
	}

	// --- struct definition ---
	if _, err := fmt.Fprintf(w, "// %s represents the YANG union type with %d member(s).\ntype %s struct {\n", typeName, len(members), typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if _, err := fmt.Fprintf(w, "\t%s %s\n", info.fieldName, info.goType); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// --- UnmarshalJSON: try members in declaration order (RFC 7950 §7.4) ---
	if _, err := fmt.Fprintf(w, "// UnmarshalJSON implements json.Unmarshaler for %s.\n// Members are tried in YANG declaration order per RFC 7950 §7.4.\nfunc (u *%s) UnmarshalJSON(b []byte) error {\n", typeName, typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if info.ptrType {
			// pointer type: unmarshal into a value then take its address
			if _, err := fmt.Fprintf(w,
				"\t{ var v %s\n\t  if err := json.Unmarshal(b, &v); err == nil { u.%s = &v; return nil } }\n",
				info.baseType, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		} else {
			// non-pointer (e.g. []byte / binary)
			if _, err := fmt.Fprintf(w,
				"\t{ var v %s\n\t  if err := json.Unmarshal(b, &v); err == nil { u.%s = v; return nil } }\n",
				info.goType, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	if _, err := fmt.Fprintf(w, "\treturn fmt.Errorf(\"%s: no union member matched %%s\", string(b))\n}\n\n", typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// --- MarshalJSON: serialize whichever field is set ---
	if _, err := fmt.Fprintf(w, "// MarshalJSON implements json.Marshaler for %s.\nfunc (u %s) MarshalJSON() ([]byte, error) {\n", typeName, typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if info.ptrType {
			if _, err := fmt.Fprintf(w, "\tif u.%s != nil { return json.Marshal(u.%s) }\n", info.fieldName, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		} else {
			// binary / slice: check len
			if _, err := fmt.Fprintf(w, "\tif len(u.%s) > 0 { return json.Marshal(u.%s) }\n", info.fieldName, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	if _, err := fmt.Fprintf(w, "\treturn []byte(\"null\"), nil\n}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// --- UnmarshalXML: try members in declaration order (RFC 7950 §7.4) ---
	if _, err := fmt.Fprintf(w,
		"// UnmarshalXML implements xml.Unmarshaler for %s.\nfunc (u *%s) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {\n"+
			"\tvar raw string\n\tif err := d.DecodeElement(&raw, &start); err != nil {\n\t\treturn err\n\t}\n"+
			"\tb := []byte(`\"` + raw + `\"`)\n",
		typeName, typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if info.ptrType {
			if _, err := fmt.Fprintf(w,
				"\t{ var v %s\n\t  if err := json.Unmarshal(b, &v); err == nil { u.%s = &v; return nil } }\n",
				info.baseType, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		} else {
			if _, err := fmt.Fprintf(w,
				"\t{ var v %s\n\t  if err := json.Unmarshal(b, &v); err == nil { u.%s = v; return nil } }\n",
				info.goType, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	if _, err := fmt.Fprintf(w, "\treturn fmt.Errorf(\"%s: no union member matched %%s\", raw)\n}\n\n", typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// --- MarshalXML: serialize whichever field is set ---
	if _, err := fmt.Fprintf(w,
		"// MarshalXML implements xml.Marshaler for %s.\nfunc (u %s) MarshalXML(e *xml.Encoder, start xml.StartElement) error {\n",
		typeName, typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if info.ptrType {
			if _, err := fmt.Fprintf(w,
				"\tif u.%s != nil { return e.EncodeElement(*u.%s, start) }\n",
				info.fieldName, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		} else {
			if _, err := fmt.Fprintf(w,
				"\tif len(u.%s) > 0 { return e.EncodeElement(u.%s, start) }\n",
				info.fieldName, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	if _, err := fmt.Fprintf(w, "\treturn nil\n}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	return nil
}

func (g *GoGenerator) writeValidationRule(w io.Writer, fieldName, ptrExpr string, typ schema.TypeDefinition) error {
	valExpr := "(*" + ptrExpr + ")"
	if typ.Name == "binary" {
		valExpr = ptrExpr // []byte is not a pointer
	}

	if len(typ.Length) > 0 {
		cond := buildLengthCondition(valExpr, typ.Name, typ.Length)
		if cond != "" {
			if _, err := fmt.Fprintf(w, "\tif %s != nil {\n\t\tif !(%s) {\n\t\t\treturn fmt.Errorf(\"%%s length out of range\", %q)\n\t\t}\n\t}\n", ptrExpr, cond, fieldName); err != nil {
				return err
			}
		}
	}
	if len(typ.Range) > 0 {
		cond := buildRangeCondition(valExpr, typ.Range)
		if cond != "" {
			if _, err := fmt.Fprintf(w, "\tif %s != nil {\n\t\tif !(%s) {\n\t\t\treturn fmt.Errorf(\"%%s value out of range\", %q)\n\t\t}\n\t}\n", ptrExpr, cond, fieldName); err != nil {
				return err
			}
		}
	}
	if len(typ.Pattern) > 0 {
		valStr := valExpr
		if typ.Name == "binary" {
			valStr = "string(" + valExpr + ")"
		}
		for _, pat := range typ.Pattern {
			if _, err := fmt.Fprintf(w, "\tif %s != nil {\n\t\tmatched, _ := regexp.MatchString(%q, %s)\n\t\tif !matched {\n\t\t\treturn fmt.Errorf(\"%%s does not match pattern\", %q)\n\t\t}\n\t}\n", ptrExpr, pat, valStr, fieldName); err != nil {
				return err
			}
		}
	}
	return nil
}

func buildLengthCondition(valExpr, yangType string, lengths []string) string {
	lengthFunc := "utf8.RuneCountInString(" + valExpr + ")"
	if yangType == "binary" {
		lengthFunc = "len(" + valExpr + ")"
	}
	var conditions []string
	for _, l := range lengths {
		parts := strings.Split(l, "|")
		var partConds []string
		for _, p := range parts {
			p = strings.TrimSpace(p)
			if strings.Contains(p, "..") {
				bounds := strings.Split(p, "..")
				minStr := strings.TrimSpace(bounds[0])
				maxStr := strings.TrimSpace(bounds[1])
				var minCond, maxCond string
				if minStr != "min" && minStr != "max" {
					minCond = fmt.Sprintf("%s >= %s", lengthFunc, minStr)
				}
				if maxStr != "max" && maxStr != "min" {
					maxCond = fmt.Sprintf("%s <= %s", lengthFunc, maxStr)
				}
				if minCond != "" && maxCond != "" {
					partConds = append(partConds, fmt.Sprintf("(%s && %s)", minCond, maxCond))
				} else if minCond != "" {
					partConds = append(partConds, minCond)
				} else if maxCond != "" {
					partConds = append(partConds, maxCond)
				}
			} else {
				if p != "min" && p != "max" {
					partConds = append(partConds, fmt.Sprintf("%s == %s", lengthFunc, p))
				}
			}
		}
		if len(partConds) > 0 {
			conditions = append(conditions, fmt.Sprintf("(%s)", strings.Join(partConds, " || ")))
		}
	}
	if len(conditions) == 0 {
		return ""
	}
	return strings.Join(conditions, " && ")
}

func buildRangeCondition(valExpr string, ranges []string) string {
	var conditions []string
	for _, r := range ranges {
		parts := strings.Split(r, "|")
		var partConds []string
		for _, p := range parts {
			p = strings.TrimSpace(p)
			if strings.Contains(p, "..") {
				bounds := strings.Split(p, "..")
				minStr := strings.TrimSpace(bounds[0])
				maxStr := strings.TrimSpace(bounds[1])
				var minCond, maxCond string
				if minStr != "min" && minStr != "max" {
					minCond = fmt.Sprintf("%s >= %s", valExpr, minStr)
				}
				if maxStr != "max" && maxStr != "min" {
					maxCond = fmt.Sprintf("%s <= %s", valExpr, maxStr)
				}
				if minCond != "" && maxCond != "" {
					partConds = append(partConds, fmt.Sprintf("(%s && %s)", minCond, maxCond))
				} else if minCond != "" {
					partConds = append(partConds, minCond)
				} else if maxCond != "" {
					partConds = append(partConds, maxCond)
				}
			} else {
				if p != "min" && p != "max" {
					partConds = append(partConds, fmt.Sprintf("%s == %s", valExpr, p))
				}
			}
		}
		if len(partConds) > 0 {
			conditions = append(conditions, fmt.Sprintf("(%s)", strings.Join(partConds, " || ")))
		}
	}
	if len(conditions) == 0 {
		return ""
	}
	return strings.Join(conditions, " && ")
}
