// Package golang provides the generator implementation for emitting Go source files.
package golang

import (
	"bytes"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/gotya/gotya/generator"
	"github.com/gotya/gotya/schema"
)

// Options holds configuration for the Go generator.
type Options struct {
	PackageName             string
	RootName                string
	GenerateFakeroot        bool
	SkipDeprecated          bool
	SkipObsolete            bool
	AddAnnotations          bool
	GenerateGetters         bool
	GenerateSetters         bool
	GeneratePopulateDefault bool
	GenerateOrderedMaps     bool
}

// GoGenerator implements the generator.Generator interface for Go struct generation.
type GoGenerator struct {
	Options *Options
}

// New creates a new GoGenerator instance.
func New(opts *Options) generator.Generator {
	if opts == nil {
		opts = &Options{}
	}
	if opts.PackageName == "" {
		opts.PackageName = "ygot" // default
	}
	if opts.RootName == "" {
		opts.RootName = "Device" // default
	}
	return &GoGenerator{
		Options: opts,
	}
}

// Generate writes Go source code for the parsed module to the provided writer.
func (g *GoGenerator) Generate(mod *schema.Module, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Code generated by gotya. DO NOT EDIT.\npackage %s\n\n", g.Options.PackageName); err != nil {
		return fmt.Errorf("failed to write package header: %w", err)
	}

	visited := make(map[string]bool)
	prefix := toCamelCaseTitle(mod.Name)
	for _, node := range mod.Nodes {
		if err := g.generateNode(node, w, visited, prefix, "", mod.Namespace, false); err != nil {
			return err
		}
	}
	return nil
}

// hasValidNodes checks if a node contains any data that should be exported taking into account its config flag.
func (g *GoGenerator) hasValidNodes(node schema.Node, configOnly bool) bool {
	if configOnly && !node.Config() {
		return false
	}
	base := node.GetBase()
	if g.Options.SkipDeprecated && base.Status != nil && *base.Status == "deprecated" {
		return false
	}
	if g.Options.SkipObsolete && base.Status != nil && *base.Status == "obsolete" {
		return false
	}

	switch n := node.(type) {
	case *schema.Leaf, *schema.LeafList, *schema.AnyXML, *schema.AnyData:
		return true
	case *schema.Container:
		for _, child := range getFlatDataNodes(n.Children) {
			if g.hasValidNodes(child, configOnly) {
				return true
			}
		}
	case *schema.List:
		for _, child := range getFlatDataNodes(n.Children) {
			if g.hasValidNodes(child, configOnly) {
				return true
			}
		}
	}
	return false
}

// GenerateDevice takes a list of validated YANG modules, aggregates them into a single root struct,
// encapsulating their configurations under Module-specific structs. It emits both Config and State representations.
func (g *GoGenerator) GenerateDevice(modules []*schema.Module, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Code generated by gotya. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"encoding/json\"\n\t\"encoding/xml\"\n\t\"fmt\"\n\t\"regexp\"\n\t\"sort\"\n\t\"strings\"\n\t\"unicode/utf8\"\n)\n\nvar (\n\t_ = json.Marshal\n\t_ = xml.Unmarshal\n\t_ = fmt.Errorf\n\t_ = regexp.MatchString\n\t_ = sort.SliceStable\n\t_ = strings.Join\n\t_ = utf8.RuneCountInString\n)\n\n", g.Options.PackageName); err != nil {
		return fmt.Errorf("failed to write package header: %w", err)
	}

	// visited tracks generated type names across both Config and State passes
	// to prevent duplicate struct / union-type declarations in the same file.
	visited := make(map[string]bool)

	for _, treeType := range []string{"Config", "State"} {
		configOnly := (treeType == "Config")

		if g.Options.GenerateFakeroot {
			if _, err := fmt.Fprintf(w, "// %s%s represents the aggregated YANG configuration.\n", g.Options.RootName, treeType); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			if _, err := fmt.Fprintf(w, "type %s%s struct {\n", g.Options.RootName, treeType); err != nil {
				return fmt.Errorf("write err: %w", err)
			}

			for _, mod := range modules {
				hasValid := false
				for _, node := range mod.Nodes {
					if g.hasValidNodes(node, configOnly) {
						hasValid = true
						break
					}
				}
				if !hasValid {
					continue // skip modules without valid fields
				}

				modStructName := toCamelCaseTitle(mod.Name) + treeType
				modFieldName := toCamelCaseTitle(mod.Name)
				xmlTag := fmt.Sprintf(" xml:\"%s,omitempty\"", mod.Name)
				if mod.Namespace != "" {
					xmlTag = fmt.Sprintf(" xml:\"%s %s,omitempty\"", mod.Namespace, mod.Name)
				}
				if _, err := fmt.Fprintf(w, "\t%s *%s `json:\"%s,omitempty\"%s`\n", modFieldName, modStructName, mod.Name, xmlTag); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
			if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
				return fmt.Errorf("write err: %w", err)
			}

			// Validate method for root Device
			if _, err := fmt.Fprintf(w, "// Validate verifies the constraints of %s%s.\nfunc (s *%s%s) Validate() error {\n", g.Options.RootName, treeType, g.Options.RootName, treeType); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			for _, mod := range modules {
				hasValid := false
				for _, node := range mod.Nodes {
					if g.hasValidNodes(node, configOnly) {
						hasValid = true
						break
					}
				}
				if !hasValid {
					continue
				}
				modFieldName := toCamelCaseTitle(mod.Name)
				if _, err := fmt.Fprintf(w, "\tif s.%s != nil {\n\t\tif err := s.%s.Validate(); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n", modFieldName, modFieldName); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
			if _, err := fmt.Fprintf(w, "\treturn nil\n}\n\n"); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}

		// Now generate each Module Struct
		for _, mod := range modules {
			hasValid := false
			for _, node := range mod.Nodes {
				if g.hasValidNodes(node, configOnly) {
					hasValid = true
					break
				}
			}
			if !hasValid {
				continue
			}

			modStructName := toCamelCaseTitle(mod.Name) + treeType
			if visited[modStructName] {
				continue
			}
			visited[modStructName] = true

			if _, err := fmt.Fprintf(w, "// %s represents the YANG module %s.\n", modStructName, mod.Name); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			if _, err := fmt.Fprintf(w, "type %s struct {\n", modStructName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}

			var modTopNodes []schema.Node
			for _, name := range getOrderedChildNames(mod.Nodes) {
				child := mod.Nodes[name]
				if !g.hasValidNodes(child, configOnly) {
					continue
				}
				modTopNodes = append(modTopNodes, child)
			}

			prefix := toCamelCaseTitle(mod.Name)
			for _, node := range modTopNodes {
				// Handle 'Validate' collision when generating the struct fields directly
				fieldName := toCamelCaseTitle(node.Name())
				if fieldName == "Validate" {
					fieldName = "ValidateField"
				}
				goType := "*string" // Default placeholder
				switch n := node.(type) {
				case *schema.Leaf:
					goType = mapYANGTypeToGo(n.Type.Name)
				case *schema.LeafList:
					goType = "[]" + mapYANGTypeToGo(n.Type.Name)
				case *schema.Container:
					goType = "*" + prefix + toCamelCaseTitle(n.Name()) + treeType
				case *schema.List:
					goType = "[]*" + prefix + toCamelCaseTitle(n.Name()) + treeType
				}
				xmlTag := fmt.Sprintf(" xml:\"%s,omitempty\"", node.Name())
				if mod.Namespace != "" {
					xmlTag = fmt.Sprintf(" xml:\"%s %s,omitempty\"", mod.Namespace, node.Name())
				}
				if _, err := fmt.Fprintf(w, "\t%s %s `json:\"%s,omitempty\"%s`\n", fieldName, goType, node.Name(), xmlTag); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
			if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
				return fmt.Errorf("write err: %w", err)
			}

			if err := g.generateValidationChecks(modStructName, modTopNodes, w); err != nil {
				return err
			}
			if g.Options.GenerateGetters {
				if err := g.generateGetters(modStructName, modTopNodes, prefix, treeType, w); err != nil {
					return err
				}
			}
			if g.Options.GenerateSetters {
				if err := g.generateSetters(modStructName, modTopNodes, prefix, treeType, w); err != nil {
					return fmt.Errorf("generateSetters err: %w", err)
				}
			}
			if g.Options.GeneratePopulateDefault {
				if err := g.generatePopulateDefault(modStructName, modTopNodes, prefix, treeType, w); err != nil {
					return fmt.Errorf("generatePopulateDefault err: %w", err)
				}
			}
			if g.Options.GenerateOrderedMaps {
				if err := g.generateSorts(modStructName, modTopNodes, w); err != nil {
					return err
				}
			}

			for _, node := range modTopNodes {
				if err := g.generateNode(node, w, visited, prefix, treeType, mod.Namespace, configOnly); err != nil {
					return err
				}
			}
		}
	}

	return nil
}

func (g *GoGenerator) generateNode(node schema.Node, w io.Writer, visited map[string]bool, prefix, suffix, namespace string, configOnly bool) error {
	switch n := node.(type) {
	case *schema.Container:
		return g.generateStruct(n.Name(), n.Description, n.Children, "container", w, visited, prefix, suffix, namespace, configOnly)
	case *schema.List:
		return g.generateStruct(n.Name()+"Entry", n.Description, n.Children, "list", w, visited, prefix, suffix, namespace, configOnly)
	case *schema.Leaf:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			ut := unionGoTypeName(prefix, n.Name())
			if !visited[ut] {
				visited[ut] = true
				if err := g.generateUnionStruct(ut, n.Type.Members, w); err != nil {
					return err
				}
			}
		} else if n.Type.Name == "bits" && len(n.Type.Bits) > 0 {
			bt := bitsGoTypeName(prefix, n.Name())
			if n.Type.TypedefName != "" {
				bt = typedefGoTypeName(prefix, n.Type.TypedefName)
			}
			if !visited[bt] {
				visited[bt] = true
				if err := g.generateBitsType(bt, n.Type.Bits, w); err != nil {
					return err
				}
			}
		} else if n.Type.Name == "enumeration" && len(n.Type.Enums) > 0 {
			et := enumGoTypeName(prefix, n.Name())
			if n.Type.TypedefName != "" {
				et = typedefGoTypeName(prefix, n.Type.TypedefName)
			}
			if !visited[et] {
				visited[et] = true
				if err := g.generateEnumType(et, n.Type.Enums, w); err != nil {
					return err
				}
			}
		} else if n.Type.TypedefName != "" && isScalarType(n.Type.Name) {
			tt := typedefGoTypeName(prefix, n.Type.TypedefName)
			if !visited[tt] {
				visited[tt] = true
				if err := g.generateTypedef(tt, mapYANGTypeToGoBase(n.Type.Name), w); err != nil {
					return err
				}
			}
		}
	case *schema.LeafList:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			ut := unionGoTypeName(prefix, n.Name())
			if !visited[ut] {
				visited[ut] = true
				if err := g.generateUnionStruct(ut, n.Type.Members, w); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (g *GoGenerator) generateStruct(name string, description *string, children map[string]schema.Node, kind string, w io.Writer, visited map[string]bool, prefix, suffix, namespace string, configOnly bool) error {
	structName := prefix + toCamelCaseTitle(name) + suffix
	if visited[structName] {
		return nil
	}
	visited[structName] = true

	// Separate non-choice flat nodes from choice nodes
	nonChoiceNodes := getNonChoiceFlatNodes(children)
	choices := getChoiceNodes(children)

	var validNonChoiceNodes []schema.Node
	for _, child := range nonChoiceNodes {
		if g.hasValidNodes(child, configOnly) {
			validNonChoiceNodes = append(validNonChoiceNodes, child)
		}
	}

	// Filter valid choices (those with at least one case with valid nodes)
	var validChoices []*schema.Choice
	for _, ch := range choices {
		hasValid := false
		for _, caseName := range getOrderedChildNames(ch.Children) {
			caseNode := ch.Children[caseName]
			caseFlat := getFlatDataNodes(caseNode.GetChildren())
			for _, cf := range caseFlat {
				if g.hasValidNodes(cf, configOnly) {
					hasValid = true
					break
				}
			}
			if hasValid {
				break
			}
		}
		if hasValid {
			validChoices = append(validChoices, ch)
		}
	}

	if len(validNonChoiceNodes) == 0 && len(validChoices) == 0 {
		return nil
	}

	// Generate choice interface + case struct types before the parent struct
	for _, ch := range validChoices {
		if err := g.generateChoiceTypes(structName, ch, w, prefix, suffix, namespace, configOnly); err != nil {
			return err
		}
	}

	if g.Options.AddAnnotations && description != nil && *description != "" {
		for line := range strings.SplitSeq(strings.TrimSpace(*description), "\n") {
			if _, err := fmt.Fprintf(w, "// %s\n", strings.TrimSpace(line)); err != nil {
				return err
			}
		}
	}
	if _, err := fmt.Fprintf(w, "// %s represents the YANG %s %s.\n", structName, kind, name); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	if _, err := fmt.Fprintf(w, "type %s struct {\n", structName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// Regular (non-choice) fields
	for _, child := range validNonChoiceNodes {
		if err := g.generateField(child, w, prefix, suffix, namespace); err != nil {
			return err
		}
	}

	// Choice interface fields
	for _, ch := range validChoices {
		choiceInterfaceName := choiceGoTypeName(structName, ch.Name())
		fieldName := toCamelCaseTitle(ch.Name())
		if _, err := fmt.Fprintf(w, "\t%s %s `json:\"-\"`\n", fieldName, choiceInterfaceName); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
	}

	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// Generate custom MarshalJSON/UnmarshalJSON if there are choices
	if len(validChoices) > 0 {
		if err := g.generateChoiceMarshalJSON(structName, validChoices, w); err != nil {
			return err
		}
		if err := g.generateChoiceUnmarshalJSON(structName, validChoices, w); err != nil {
			return err
		}
	}

	// Only validate non-choice fields; choice case fields are in their own structs
	if err := g.generateValidationChecks(structName, validNonChoiceNodes, w); err != nil {
		return err
	}
	if g.Options.GenerateGetters {
		if err := g.generateGetters(structName, validNonChoiceNodes, prefix, suffix, w); err != nil {
			return fmt.Errorf("generateGetters err: %w", err)
		}
	}
	if g.Options.GenerateSetters {
		if err := g.generateSetters(structName, validNonChoiceNodes, prefix, suffix, w); err != nil {
			return fmt.Errorf("generateSetters err: %w", err)
		}
	}
	if g.Options.GeneratePopulateDefault {
		if err := g.generatePopulateDefault(structName, validNonChoiceNodes, prefix, suffix, w); err != nil {
			return fmt.Errorf("generatePopulateDefault err: %w", err)
		}
	}
	if g.Options.GenerateOrderedMaps {
		if err := g.generateSorts(structName, validNonChoiceNodes, w); err != nil {
			return err
		}
	}

	// Recurse for nested structs in non-choice nodes
	for _, child := range validNonChoiceNodes {
		if err := g.generateNode(child, w, visited, prefix, suffix, namespace, configOnly); err != nil {
			return err
		}
	}
	// Recurse for nested structs inside choice cases
	for _, ch := range validChoices {
		for _, caseName := range getOrderedChildNames(ch.Children) {
			caseNode := ch.Children[caseName]
			for _, caseChild := range getFlatDataNodes(caseNode.GetChildren()) {
				if g.hasValidNodes(caseChild, configOnly) {
					if err := g.generateNode(caseChild, w, visited, prefix, suffix, namespace, configOnly); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

func (g *GoGenerator) generateField(node schema.Node, w io.Writer, prefix, suffix, namespace string) error {
	fieldName := toCamelCaseTitle(node.Name())
	if fieldName == "Validate" {
		fieldName = "ValidateField"
	}
	goType := "*string" // Default placeholder

	switch n := node.(type) {
	case *schema.Leaf:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			goType = "*" + unionGoTypeName(prefix, n.Name())
		} else if n.Type.Name == "bits" && len(n.Type.Bits) > 0 {
			if n.Type.TypedefName != "" {
				goType = "*" + typedefGoTypeName(prefix, n.Type.TypedefName)
			} else {
				goType = "*" + bitsGoTypeName(prefix, n.Name())
			}
		} else if n.Type.Name == "enumeration" && len(n.Type.Enums) > 0 {
			if n.Type.TypedefName != "" {
				goType = "*" + typedefGoTypeName(prefix, n.Type.TypedefName)
			} else {
				goType = "*" + enumGoTypeName(prefix, n.Name())
			}
		} else if n.Type.TypedefName != "" && isScalarType(n.Type.Name) {
			goType = "*" + typedefGoTypeName(prefix, n.Type.TypedefName)
		} else {
			goType = mapYANGTypeToGo(n.Type.Name)
		}
	case *schema.LeafList:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			goType = "[]" + unionGoTypeName(prefix, n.Name())
		} else {
			goType = "[]" + mapYANGTypeToGo(n.Type.Name)
		}
	case *schema.Container:
		goType = "*" + prefix + toCamelCaseTitle(n.Name()) + suffix
	case *schema.List:
		goType = "[]*" + prefix + toCamelCaseTitle(n.Name()) + "Entry" + suffix
	}

	xmlTag := fmt.Sprintf(" xml:\"%s,omitempty\"", node.Name())
	if namespace != "" {
		xmlTag = fmt.Sprintf(" xml:\"%s %s,omitempty\"", namespace, node.Name())
	}

	moduleName := node.GetBase().ModuleName
	yangTag := fmt.Sprintf(" yang:\"%s:%s\"", moduleName, node.Name())

	if g.Options.AddAnnotations && node.GetBase().Description != nil && *node.GetBase().Description != "" {
		for line := range strings.SplitSeq(strings.TrimSpace(*node.GetBase().Description), "\n") {
			if _, err := fmt.Fprintf(w, "\t// %s\n", strings.TrimSpace(line)); err != nil {
				return err
			}
		}
	}

	if _, err := fmt.Fprintf(w, "\t%s %s `json:\"%s,omitempty\"%s%s`\n", fieldName, goType, node.Name(), xmlTag, yangTag); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	return nil
}

func toCamelCaseTitle(s string) string {
	s = strings.ReplaceAll(s, ".", "_")
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func mapYANGTypeToGo(yangType string) string {
	switch yangType {
	case "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64":
		return "*" + yangType
	case "boolean":
		return "*bool"
	case "decimal64":
		return "*float64"
	case "empty":
		return "*bool"
	case "binary":
		return "[]byte"
	case "bits":
		// Fallback when bits has no named members — treat as string
		return "*string"
	case "enumeration":
		// Fallback when enumeration has no named values — treat as string
		return "*string"
	default:
		return "*string"
	}
}

// bitsGoTypeName generates the Go type name for a YANG bits type.
func bitsGoTypeName(prefix, nodeName string) string {
	return prefix + toCamelCaseTitle(nodeName) + "Bits"
}

// enumGoTypeName generates the Go type name for a YANG enumeration type.
func enumGoTypeName(prefix, nodeName string) string {
	return prefix + toCamelCaseTitle(nodeName) + "Enum"
}

// typedefGoTypeName generates the Go type name for a YANG typedef.
func typedefGoTypeName(prefix, typedefName string) string {
	return prefix + toCamelCaseTitle(typedefName)
}

// isScalarType returns true for built-in YANG types that map to Go scalar types.
func isScalarType(name string) bool {
	switch name {
	case "int8", "int16", "int32", "int64",
		"uint8", "uint16", "uint32", "uint64",
		"boolean", "decimal64", "string", "binary", "empty":
		return true
	default:
		return false
	}
}

// mapYANGTypeToGoBase returns the Go base type name without pointer wrapper.
func mapYANGTypeToGoBase(yangType string) string {
	switch yangType {
	case "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64":
		return yangType
	case "boolean":
		return "bool"
	case "decimal64":
		return "float64"
	case "empty":
		return "bool"
	case "binary":
		return "[]byte"
	case "string":
		return "string"
	default:
		return "string"
	}
}

func (g *GoGenerator) generateValidationChecks(structName string, flatNodes []schema.Node, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Validate verifies the constraints of %s.\n", structName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	if _, err := fmt.Fprintf(w, "func (s *%s) Validate() error {\n", structName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	for _, node := range flatNodes {
		fieldName := toCamelCaseTitle(node.Name())
		if (strings.HasSuffix(structName, "Config") || strings.HasSuffix(structName, "State")) && fieldName == "Validate" {
			fieldName = "ValidateField"
		}
		// In case any internal field is natively named Validate, we handle it during field generation
		if fieldName == "Validate" {
			fieldName = "ValidateField"
		}

		switch n := node.(type) {
		case *schema.Container:
			if _, err := fmt.Fprintf(w, "\tif s.%s != nil {\n\t\tif err := s.%s.Validate(); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n", fieldName, fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		case *schema.List:
			if _, err := fmt.Fprintf(w, "\tfor _, item := range s.%s {\n\t\tif item != nil {\n\t\t\tif err := item.Validate(); err != nil {\n\t\t\t\treturn err\n\t\t\t}\n\t\t}\n\t}\n", fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		case *schema.Leaf:
			if err := g.writeValidationRule(w, fieldName, "s."+fieldName, n.Type); err != nil {
				return err
			}
		case *schema.LeafList:
			if len(n.Type.Length) > 0 || len(n.Type.Range) > 0 || len(n.Type.Pattern) > 0 {
				if _, err := fmt.Fprintf(w, "\tfor _, item := range s.%s {\n", fieldName); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
				if err := g.writeValidationRule(w, fieldName, "item", n.Type); err != nil {
					return err
				}
				if _, err := fmt.Fprintf(w, "\t}\n"); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
		}
	}

	if _, err := fmt.Fprintf(w, "\treturn nil\n}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	return nil
}

// getOrderedChildNames returns the names of children sorted by their schema definition order.
func getOrderedChildNames(children map[string]schema.Node) []string {
	type nameOrder struct {
		name  string
		order int
	}
	list := make([]nameOrder, 0, len(children))
	for name, node := range children {
		list = append(list, nameOrder{
			name:  name,
			order: node.GetBase().Order,
		})
	}
	sort.Slice(list, func(i, j int) bool {
		return list[i].order < list[j].order
	})

	names := make([]string, len(list))
	for i, item := range list {
		names[i] = item.name
	}
	return names
}

// getFlatDataNodes recurses into Choice and Case nodes to extract the actual
// data tree children that participate in JSON/XML representations natively.
func getFlatDataNodes(nodes map[string]schema.Node) []schema.Node {
	var result []schema.Node
	seen := make(map[string]bool)

	var walk func(ns map[string]schema.Node)
	walk = func(ns map[string]schema.Node) {
		for _, name := range getOrderedChildNames(ns) {
			node := ns[name]
			switch n := node.(type) {
			case *schema.Choice:
				for _, caseName := range getOrderedChildNames(n.Children) {
					caseNode := n.Children[caseName]
					walk(caseNode.GetChildren())
				}
			case *schema.Case:
				walk(n.Children)
			default:
				if !seen[node.Name()] {
					seen[node.Name()] = true
					result = append(result, node)
				}
			}
		}
	}
	walk(nodes)
	return result
}

// getChoiceNodes returns only the Choice nodes from a children map, in order.
func getChoiceNodes(children map[string]schema.Node) []*schema.Choice {
	var choices []*schema.Choice
	for _, name := range getOrderedChildNames(children) {
		if c, ok := children[name].(*schema.Choice); ok {
			choices = append(choices, c)
		}
	}
	return choices
}

// getNonChoiceFlatNodes returns flat data nodes excluding any that live inside choices.
func getNonChoiceFlatNodes(nodes map[string]schema.Node) []schema.Node {
	var result []schema.Node
	seen := make(map[string]bool)
	for _, name := range getOrderedChildNames(nodes) {
		node := nodes[name]
		switch node.(type) {
		case *schema.Choice:
			// Skip — handled separately
		case *schema.Case:
			// Should not appear at top level, but skip
		default:
			if !seen[node.Name()] {
				seen[node.Name()] = true
				result = append(result, node)
			}
		}
	}
	return result
}

// choiceGoTypeName generates the Go interface name for a YANG choice.
func choiceGoTypeName(parentStructName, choiceName string) string {
	return parentStructName + toCamelCaseTitle(choiceName) + "Choice"
}

// caseGoTypeName generates the Go struct name for a YANG case.
func caseGoTypeName(choiceTypeName, caseName string) string {
	return choiceTypeName + toCamelCaseTitle(caseName)
}

// unionGoTypeName builds a unique Go type name for a union leaf.
func unionGoTypeName(prefix, leafName string) string {
	return prefix + toCamelCaseTitle(leafName) + "Union"
}

// generateUnionStruct emits a union wrapper struct with one optional field per
// member type (in YANG declaration order) and the corresponding UnmarshalJSON /
// MarshalJSON methods that enforce RFC 7950 §7.4 ordered matching.
func (g *GoGenerator) generateUnionStruct(typeName string, members []schema.TypeDefinition, w io.Writer) error {
	// Build per-member field info: field name, Go type, unmarshal snippet.
	type memberInfo struct {
		fieldName string
		goType    string
		ptrType   bool   // true when the Go type is a pointer (*T)
		baseType  string // T without the leading *
	}
	seen := make(map[string]int)
	infos := make([]memberInfo, 0, len(members))
	for _, m := range members {
		goType := mapYANGTypeToGo(m.Name)
		// Derive a unique field name from the YANG type name.
		// Strip any module prefix (e.g. "bbf-qos-t:traffic-class-id" → "traffic-class-id")
		localName := m.Name
		if idx := strings.LastIndex(localName, ":"); idx >= 0 {
			localName = localName[idx+1:]
		}
		base := toCamelCaseTitle(localName)
		if _, exists := seen[base]; exists {
			seen[base]++
			base = fmt.Sprintf("%s%d", base, seen[base])
		} else {
			seen[base] = 0
		}
		isPtr := strings.HasPrefix(goType, "*")
		baseType := strings.TrimPrefix(goType, "*")
		infos = append(infos, memberInfo{
			fieldName: base,
			goType:    goType,
			ptrType:   isPtr,
			baseType:  baseType,
		})
	}

	// --- struct definition ---
	if _, err := fmt.Fprintf(w, "// %s represents the YANG union type with %d member(s).\ntype %s struct {\n", typeName, len(members), typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if _, err := fmt.Fprintf(w, "\t%s %s\n", info.fieldName, info.goType); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// --- UnmarshalJSON: try members in declaration order (RFC 7950 §7.4) ---
	if _, err := fmt.Fprintf(w, "// UnmarshalJSON implements json.Unmarshaler for %s.\n// Members are tried in YANG declaration order per RFC 7950 §7.4.\nfunc (u *%s) UnmarshalJSON(b []byte) error {\n", typeName, typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if info.ptrType {
			// pointer type: unmarshal into a value then take its address
			if _, err := fmt.Fprintf(w,
				"\t{ var v %s\n\t  if err := json.Unmarshal(b, &v); err == nil { u.%s = &v; return nil } }\n",
				info.baseType, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		} else {
			// non-pointer (e.g. []byte / binary)
			if _, err := fmt.Fprintf(w,
				"\t{ var v %s\n\t  if err := json.Unmarshal(b, &v); err == nil { u.%s = v; return nil } }\n",
				info.goType, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	if _, err := fmt.Fprintf(w, "\treturn fmt.Errorf(\"%s: no union member matched %%s\", string(b))\n}\n\n", typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// --- MarshalJSON: serialize whichever field is set ---
	if _, err := fmt.Fprintf(w, "// MarshalJSON implements json.Marshaler for %s.\nfunc (u %s) MarshalJSON() ([]byte, error) {\n", typeName, typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if info.ptrType {
			if _, err := fmt.Fprintf(w, "\tif u.%s != nil { return json.Marshal(u.%s) }\n", info.fieldName, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		} else {
			// binary / slice: check len
			if _, err := fmt.Fprintf(w, "\tif len(u.%s) > 0 { return json.Marshal(u.%s) }\n", info.fieldName, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	if _, err := fmt.Fprintf(w, "\treturn []byte(\"null\"), nil\n}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// --- UnmarshalXML: try members in declaration order (RFC 7950 §7.4) ---
	if _, err := fmt.Fprintf(w,
		"// UnmarshalXML implements xml.Unmarshaler for %s.\nfunc (u *%s) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {\n"+
			"\tvar raw string\n\tif err := d.DecodeElement(&raw, &start); err != nil {\n\t\treturn err\n\t}\n"+
			"\tb := []byte(`\"` + raw + `\"`)\n",
		typeName, typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if info.ptrType {
			if _, err := fmt.Fprintf(w,
				"\t{ var v %s\n\t  if err := json.Unmarshal(b, &v); err == nil { u.%s = &v; return nil } }\n",
				info.baseType, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		} else {
			if _, err := fmt.Fprintf(w,
				"\t{ var v %s\n\t  if err := json.Unmarshal(b, &v); err == nil { u.%s = v; return nil } }\n",
				info.goType, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	if _, err := fmt.Fprintf(w, "\treturn fmt.Errorf(\"%s: no union member matched %%s\", raw)\n}\n\n", typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// --- MarshalXML: serialize whichever field is set ---
	if _, err := fmt.Fprintf(w,
		"// MarshalXML implements xml.Marshaler for %s.\nfunc (u %s) MarshalXML(e *xml.Encoder, start xml.StartElement) error {\n",
		typeName, typeName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	for _, info := range infos {
		if info.ptrType {
			if _, err := fmt.Fprintf(w,
				"\tif u.%s != nil { return e.EncodeElement(*u.%s, start) }\n",
				info.fieldName, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		} else {
			if _, err := fmt.Fprintf(w,
				"\tif len(u.%s) > 0 { return e.EncodeElement(u.%s, start) }\n",
				info.fieldName, info.fieldName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	if _, err := fmt.Fprintf(w, "\treturn nil\n}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	return nil
}

func (g *GoGenerator) writeValidationRule(w io.Writer, fieldName, ptrExpr string, typ schema.TypeDefinition) error {
	valExpr := "*" + ptrExpr
	if typ.Name == "binary" {
		valExpr = ptrExpr // []byte is not a pointer
	}

	// When the type is a typedef, cast to the base Go type for
	// constraint functions that expect primitive types.
	if typ.TypedefName != "" && isScalarType(typ.Name) {
		baseType := mapYANGTypeToGoBase(typ.Name)
		valExpr = baseType + "(" + valExpr + ")"
	}

	if len(typ.Length) > 0 {
		cond := buildLengthCondition(valExpr, typ.Name, typ.Length)
		if cond != "" {
			if _, err := fmt.Fprintf(w, "\tif %s != nil {\n\t\tif !(%s) {\n\t\t\treturn fmt.Errorf(\"%%s length out of range\", %q)\n\t\t}\n\t}\n", ptrExpr, cond, fieldName); err != nil {
				return err
			}
		}
	}
	if len(typ.Range) > 0 {
		cond := buildRangeCondition(valExpr, typ.Range)
		if cond != "" {
			if _, err := fmt.Fprintf(w, "\tif %s != nil {\n\t\tif !(%s) {\n\t\t\treturn fmt.Errorf(\"%%s value out of range\", %q)\n\t\t}\n\t}\n", ptrExpr, cond, fieldName); err != nil {
				return err
			}
		}
	}
	if len(typ.Pattern) > 0 {
		valStr := valExpr
		if typ.Name == "binary" {
			valStr = "string(" + valExpr + ")"
		}
		for _, pat := range typ.Pattern {
			if _, err := fmt.Fprintf(w, "\tif %s != nil {\n\t\tmatched, _ := regexp.MatchString(%q, %s)\n\t\tif !matched {\n\t\t\treturn fmt.Errorf(\"%%s does not match pattern\", %q)\n\t\t}\n\t}\n", ptrExpr, pat, valStr, fieldName); err != nil {
				return err
			}
		}
	}
	return nil
}

func buildLengthCondition(valExpr, yangType string, lengths []string) string {
	lengthFunc := "utf8.RuneCountInString(" + valExpr + ")"
	if yangType == "binary" {
		lengthFunc = "len(" + valExpr + ")"
	}
	return buildBoundsCondition(lengthFunc, lengths)
}

func buildRangeCondition(valExpr string, ranges []string) string {
	return buildBoundsCondition(valExpr, ranges)
}

func buildBoundsCondition(valExpr string, boundsList []string) string {
	var conditions []string
	for _, b := range boundsList {
		var partConds []string
		for p := range strings.SplitSeq(b, "|") {
			p = strings.TrimSpace(p)
			if strings.Contains(p, "..") {
				bounds := strings.Split(p, "..")
				minStr := strings.TrimSpace(bounds[0])
				maxStr := strings.TrimSpace(bounds[1])
				var minCond, maxCond string
				if minStr != "min" && minStr != "max" {
					minCond = fmt.Sprintf("%s >= %s", valExpr, minStr)
				}
				if maxStr != "max" && maxStr != "min" {
					maxCond = fmt.Sprintf("%s <= %s", valExpr, maxStr)
				}
				if minCond != "" && maxCond != "" {
					partConds = append(partConds, fmt.Sprintf("%s && %s", minCond, maxCond))
				} else if minCond != "" {
					partConds = append(partConds, minCond)
				} else if maxCond != "" {
					partConds = append(partConds, maxCond)
				}
			} else {
				if p != "min" && p != "max" {
					partConds = append(partConds, fmt.Sprintf("%s == %s", valExpr, p))
				}
			}
		}
		if len(partConds) > 0 {
			conditions = append(conditions, strings.Join(partConds, " || "))
		}
	}
	if len(conditions) == 0 {
		return ""
	}
	if len(conditions) > 1 {
		for i, c := range conditions {
			conditions[i] = fmt.Sprintf("(%s)", c)
		}
	}
	return strings.Join(conditions, " && ")
}

// generateGetters generates safe nil-checking accessor methods for struct fields.
func (g *GoGenerator) generateGetters(structName string, nodes []schema.Node, prefix, suffix string, w io.Writer) error {
	for _, node := range nodes {
		fieldName := toCamelCaseTitle(node.Name())
		if fieldName == "Validate" {
			fieldName = "ValidateField"
		}

		goType, isPtr, isContainer := g.resolveFieldTypeInfo(node, prefix, suffix)

		// If it's a container or list, we return the pointer/slice/map directly.
		// If it's a primitive leaf pointer, we return the value type.
		returnType := goType
		if isPtr && !isContainer {
			returnType = strings.TrimPrefix(goType, "*")
		}

		if _, err := fmt.Fprintf(w, "// Get%s retrieves the value of the field %s from its parent, returning its default or zero value if unset.\n", fieldName, fieldName); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "func (s *%s) Get%s() %s {\n", structName, fieldName, returnType); err != nil {
			return err
		}

		if isPtr && !isContainer {
			// Union is an interface
			if strings.Contains(returnType, "Union") {
				if _, err := fmt.Fprintf(w, "\tif s == nil || s.%s == nil {\n\t\treturn nil\n\t}\n\treturn s.%s\n}\n\n", fieldName, fieldName); err != nil {
					return err
				}
			} else {
				if _, err := fmt.Fprintf(w, "\tif s == nil || s.%s == nil {\n\t\tvar zero %s\n\t\treturn zero\n\t}\n\treturn *s.%s\n}\n\n", fieldName, returnType, fieldName); err != nil {
					return err
				}
			}
		} else {
			// slices, maps, containers -> return directly with nil check
			if _, err := fmt.Fprintf(w, "\tif s == nil {\n\t\tvar zero %s\n\t\treturn zero\n\t}\n\treturn s.%s\n}\n\n", returnType, fieldName); err != nil {
				return err
			}
		}
	}
	return nil
}

// resolveFieldTypeInfo reconstructs the Go type of a node exactly as it's emitted in the struct fields.
func (g *GoGenerator) resolveFieldTypeInfo(node schema.Node, prefix, suffix string) (goType string, isPtr, isContainer bool) {
	switch n := node.(type) {
	case *schema.Leaf:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			goType = unionGoTypeName(prefix, n.Name())
			isPtr = true // For unions, we usually store as interface, effectively a pointer
		} else {
			goType = mapYANGTypeToGo(n.Type.Name)
			if strings.HasPrefix(goType, "*") {
				isPtr = true
			}
		}
	case *schema.LeafList:
		if n.Type.Name == "union" && len(n.Type.Members) > 0 {
			goType = "[]" + unionGoTypeName(prefix, n.Name())
		} else {
			goType = "[]" + mapYANGTypeToGo(n.Type.Name)
		}
	case *schema.Container:
		goType = "*" + prefix + toCamelCaseTitle(n.Name()) + suffix
		isPtr = true
		isContainer = true
	case *schema.List:
		goType = "[]*" + prefix + toCamelCaseTitle(n.Name()) + "Entry" + suffix
		isContainer = true
	}
	return goType, isPtr, isContainer
}

// generateSetters generates setter methods for struct fields.
func (g *GoGenerator) generateSetters(structName string, nodes []schema.Node, prefix, suffix string, w io.Writer) error {
	for _, node := range nodes {
		fieldName := toCamelCaseTitle(node.Name())
		if fieldName == "Validate" {
			fieldName = "ValidateField"
		}

		goType, isPtr, isContainer := g.resolveFieldTypeInfo(node, prefix, suffix)

		// Setters for pointers (leaves) usually take the base value, and the setter wraps it in a pointer.
		// For slices, maps, containers, they take the pointer/slice/map directly.
		argType := goType
		if isPtr && !isContainer {
			argType = strings.TrimPrefix(goType, "*")
		}

		if _, err := fmt.Fprintf(w, "// Set%s sets the value of the field %s.\n", fieldName, fieldName); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "func (s *%s) Set%s(v %s) {\n", structName, fieldName, argType); err != nil {
			return err
		}

		if isPtr && !isContainer && !strings.Contains(argType, "Union") {
			if _, err := fmt.Fprintf(w, "\ts.%s = &v\n}\n\n", fieldName); err != nil {
				return err
			}
		} else {
			if _, err := fmt.Fprintf(w, "\ts.%s = v\n}\n\n", fieldName); err != nil {
				return err
			}
		}
	}
	return nil
}

// generatePopulateDefault generates a method that populates nil fields with their YANG default values.
func (g *GoGenerator) generatePopulateDefault(structName string, nodes []schema.Node, prefix, suffix string, w io.Writer) error {
	var body bytes.Buffer
	hasDefaults := false

	for _, node := range nodes {
		fieldName := toCamelCaseTitle(node.Name())
		if fieldName == "Validate" {
			fieldName = "ValidateField"
		}

		switch n := node.(type) {
		case *schema.Leaf:
			if n.Default != nil {
				goType, _, _ := g.resolveFieldTypeInfo(node, prefix, suffix)
				baseType := strings.TrimPrefix(goType, "*")

				// parse the default string into the go type
				if strings.Contains(baseType, "Union") {
					continue
				}

				valStr := ""
				switch baseType {
				case "string":
					valStr = fmt.Sprintf(`"%s"`, *n.Default)
				case "bool":
					valStr = *n.Default
				default:
					valStr = fmt.Sprintf("%s(%s)", baseType, *n.Default)
				}

				fmt.Fprintf(&body, "\tif s.%s == nil {\n\t\tvar v %s = %s\n\t\ts.%s = &v\n\t}\n", fieldName, baseType, valStr, fieldName)
				hasDefaults = true
			}
		}
	}

	if hasDefaults {
		if _, err := fmt.Fprintf(w, "// PopulateDefaults recursively populates nil fields in %s with default values.\n", structName); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "func (s *%s) PopulateDefaults() {\n%s}\n\n", structName, body.String()); err != nil {
			return err
		}
	}
	return nil
}

// generateSorts generates methods to state if a list or leaf-list is ordered, and by what semantics.
func (g *GoGenerator) generateSorts(structName string, nodes []schema.Node, w io.Writer) error {
	for _, node := range nodes {
		fieldName := toCamelCaseTitle(node.Name())
		if fieldName == "Validate" {
			fieldName = "ValidateField"
		}

		orderedBy := "system"
		switch n := node.(type) {
		case *schema.List:
			if n.OrderedBy != nil {
				orderedBy = *n.OrderedBy
			}
		case *schema.LeafList:
			if n.OrderedBy != nil {
				orderedBy = *n.OrderedBy
			}
		default:
			continue
		}

		isOrdered := orderedBy == "user"

		if _, err := fmt.Fprintf(w, "// IsOrdered%s returns true if the %s slice is ordered-by user.\n", fieldName, fieldName); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "func (s *%s) IsOrdered%s() bool {\n", structName, fieldName); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "\treturn %v\n", isOrdered); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
			return err
		}

		if _, err := fmt.Fprintf(w, "// Order%s returns the ordered-by semantics of the %s slice.\n", fieldName, fieldName); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "func (s *%s) Order%s() string {\n", structName, fieldName); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "\treturn \"%s\"\n", orderedBy); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
			return err
		}
	}
	return nil
}

// generateBitsType generates a named uint64 type for a YANG bits leaf,
// with iota constants, name/value maps, bitwise helpers, and JSON marshaling.
func (g *GoGenerator) generateBitsType(typeName string, bits []string, w io.Writer) error {
	// Type declaration
	if _, err := fmt.Fprintf(w, "// %s represents the YANG bits type with %d bit(s).\ntype %s uint64\n\n", typeName, len(bits), typeName); err != nil {
		return err
	}

	// Constants using iota
	if _, err := fmt.Fprintf(w, "const (\n"); err != nil {
		return err
	}
	for i, bit := range bits {
		constName := typeName + toCamelCaseTitle(bit)
		if i == 0 {
			if _, err := fmt.Fprintf(w, "\t%s %s = 1 << iota\n", constName, typeName); err != nil {
				return err
			}
		} else {
			if _, err := fmt.Fprintf(w, "\t%s\n", constName); err != nil {
				return err
			}
		}
	}
	if _, err := fmt.Fprintf(w, ")\n\n"); err != nil {
		return err
	}

	// Lowercase variable name for maps
	lowerName := strings.ToLower(typeName[:1]) + typeName[1:]

	// Name to value map
	if _, err := fmt.Fprintf(w, "var %sNameMap = map[string]%s{\n", lowerName, typeName); err != nil {
		return err
	}
	for _, bit := range bits {
		constName := typeName + toCamelCaseTitle(bit)
		if _, err := fmt.Fprintf(w, "\t\"%s\": %s,\n", bit, constName); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return err
	}

	// Value to name map
	if _, err := fmt.Fprintf(w, "var %sValueMap = map[%s]string{\n", lowerName, typeName); err != nil {
		return err
	}
	for _, bit := range bits {
		constName := typeName + toCamelCaseTitle(bit)
		if _, err := fmt.Fprintf(w, "\t%s: \"%s\",\n", constName, bit); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return err
	}

	// Has method
	if _, err := fmt.Fprintf(w, "// Has returns true if the given bit is set.\nfunc (b %s) Has(flag %s) bool { return b&flag != 0 }\n\n", typeName, typeName); err != nil {
		return err
	}

	// Set method
	if _, err := fmt.Fprintf(w, "// Set returns the bits value with the given flag set.\nfunc (b %s) Set(flag %s) %s { return b | flag }\n\n", typeName, typeName, typeName); err != nil {
		return err
	}

	// Clear method
	if _, err := fmt.Fprintf(w, "// Clear returns the bits value with the given flag cleared.\nfunc (b %s) Clear(flag %s) %s { return b &^ flag }\n\n", typeName, typeName, typeName); err != nil {
		return err
	}

	// String method
	if _, err := fmt.Fprintf(w, "// String returns the space-separated names of all set bits.\nfunc (b %s) String() string {\n\tvar names []string\n\tfor val, name := range %sValueMap {\n\t\tif b&val != 0 {\n\t\t\tnames = append(names, name)\n\t\t}\n\t}\n\treturn strings.Join(names, \" \")\n}\n\n", typeName, lowerName); err != nil {
		return err
	}

	// MarshalJSON
	if _, err := fmt.Fprintf(w, "// MarshalJSON implements json.Marshaler for %s.\n// RFC 7951 §6.7: bits are encoded as a space-separated string of set bit names.\nfunc (b %s) MarshalJSON() ([]byte, error) {\n\treturn json.Marshal(b.String())\n}\n\n", typeName, typeName); err != nil {
		return err
	}

	// UnmarshalJSON
	if _, err := fmt.Fprintf(w, "// UnmarshalJSON implements json.Unmarshaler for %s.\nfunc (b *%s) UnmarshalJSON(data []byte) error {\n\tvar s string\n\tif err := json.Unmarshal(data, &s); err != nil {\n\t\treturn err\n\t}\n\tif s == \"\" {\n\t\t*b = 0\n\t\treturn nil\n\t}\n\tfor name := range strings.SplitSeq(s, \" \") {\n\t\tif val, ok := %sNameMap[name]; ok {\n\t\t\t*b = b.Set(val)\n\t\t} else {\n\t\t\treturn fmt.Errorf(\"unknown bit name %%q for %s\", name)\n\t\t}\n\t}\n\treturn nil\n}\n", typeName, typeName, lowerName, typeName); err != nil {
		return err
	}

	return nil
}

// generateEnumType generates a named uint64 type for a YANG enumeration leaf,
// with iota constants, name/value maps, and JSON marshaling.
func (g *GoGenerator) generateEnumType(typeName string, enums []string, w io.Writer) error {
	// Type declaration
	if _, err := fmt.Fprintf(w, "// %s represents the YANG enumeration type with %d value(s).\ntype %s uint64\n\n", typeName, len(enums), typeName); err != nil {
		return err
	}

	// Constants using iota (sequential, not bit-shifted)
	if _, err := fmt.Fprintf(w, "const (\n"); err != nil {
		return err
	}
	for i, enum := range enums {
		constName := typeName + toCamelCaseTitle(enum)
		if i == 0 {
			if _, err := fmt.Fprintf(w, "\t%s %s = iota\n", constName, typeName); err != nil {
				return err
			}
		} else {
			if _, err := fmt.Fprintf(w, "\t%s\n", constName); err != nil {
				return err
			}
		}
	}
	if _, err := fmt.Fprintf(w, ")\n\n"); err != nil {
		return err
	}

	// Lowercase variable name for maps
	lowerName := strings.ToLower(typeName[:1]) + typeName[1:]

	// Name to value map
	if _, err := fmt.Fprintf(w, "var %sNameMap = map[string]%s{\n", lowerName, typeName); err != nil {
		return err
	}
	for _, enum := range enums {
		constName := typeName + toCamelCaseTitle(enum)
		if _, err := fmt.Fprintf(w, "\t\"%s\": %s,\n", enum, constName); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return err
	}

	// Value to name map
	if _, err := fmt.Fprintf(w, "var %sValueMap = map[%s]string{\n", lowerName, typeName); err != nil {
		return err
	}
	for _, enum := range enums {
		constName := typeName + toCamelCaseTitle(enum)
		if _, err := fmt.Fprintf(w, "\t%s: \"%s\",\n", constName, enum); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return err
	}

	// String method
	if _, err := fmt.Fprintf(w, "// String returns the YANG name of the enum value.\nfunc (e %s) String() string {\n\tif name, ok := %sValueMap[e]; ok {\n\t\treturn name\n\t}\n\treturn fmt.Sprintf(\"%s(%%d)\", uint64(e))\n}\n\n", typeName, lowerName, typeName); err != nil {
		return err
	}

	// MarshalJSON — enum → string value
	if _, err := fmt.Fprintf(w, "// MarshalJSON implements json.Marshaler for %s.\nfunc (e %s) MarshalJSON() ([]byte, error) {\n\treturn json.Marshal(e.String())\n}\n\n", typeName, typeName); err != nil {
		return err
	}

	// UnmarshalJSON — string → enum
	if _, err := fmt.Fprintf(w, "// UnmarshalJSON implements json.Unmarshaler for %s.\nfunc (e *%s) UnmarshalJSON(data []byte) error {\n\tvar s string\n\tif err := json.Unmarshal(data, &s); err != nil {\n\t\treturn err\n\t}\n\tif val, ok := %sNameMap[s]; ok {\n\t\t*e = val\n\t\treturn nil\n\t}\n\treturn fmt.Errorf(\"unknown enum value %%q for %s\", s)\n}\n\n", typeName, typeName, lowerName, typeName); err != nil {
		return err
	}

	return nil
}

// generateTypedef generates a simple named type for a YANG typedef
// that wraps a scalar Go base type (e.g., type PortNumber uint16).
func (g *GoGenerator) generateTypedef(typeName, baseGoType string, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// %s is a named Go type for the YANG typedef.\ntype %s %s\n\n", typeName, typeName, baseGoType); err != nil {
		return err
	}
	return nil
}

// generateChoiceTypes generates the interface and case structs for a YANG choice.
func (g *GoGenerator) generateChoiceTypes(parentStructName string, ch *schema.Choice, w io.Writer, prefix, suffix, namespace string, configOnly bool) error {
	choiceIface := choiceGoTypeName(parentStructName, ch.Name())

	// Interface
	if _, err := fmt.Fprintf(w, "// %s is the interface for YANG choice \"%s\".\ntype %s interface {\n\tis%s()\n}\n\n", choiceIface, ch.Name(), choiceIface, choiceIface); err != nil {
		return err
	}

	// Generate a case struct for each case
	for _, caseName := range getOrderedChildNames(ch.Children) {
		caseNode := ch.Children[caseName]
		caseType := caseGoTypeName(choiceIface, caseName)
		caseChildren := getFlatDataNodes(caseNode.GetChildren())

		var validChildren []schema.Node
		for _, child := range caseChildren {
			if g.hasValidNodes(child, configOnly) {
				validChildren = append(validChildren, child)
			}
		}
		if len(validChildren) == 0 {
			continue
		}

		// Case struct
		if _, err := fmt.Fprintf(w, "// %s represents case \"%s\" of choice \"%s\".\ntype %s struct {\n", caseType, caseName, ch.Name(), caseType); err != nil {
			return err
		}
		for _, child := range validChildren {
			if err := g.generateField(child, w, prefix, suffix, namespace); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
			return err
		}

		// Marker method
		if _, err := fmt.Fprintf(w, "func (%s) is%s() {}\n\n", caseType, choiceIface); err != nil {
			return err
		}
	}

	return nil
}

// generateChoiceMarshalJSON generates a custom MarshalJSON for structs with choice fields.
// It inlines the active case's fields alongside the struct's own fields.
func (g *GoGenerator) generateChoiceMarshalJSON(structName string, choices []*schema.Choice, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// MarshalJSON implements json.Marshaler for %s.\n// Inlines choice case fields into the parent JSON object.\nfunc (s *%s) MarshalJSON() ([]byte, error) {\n", structName, structName); err != nil {
		return err
	}

	// Build an aux struct with regular fields only
	if _, err := fmt.Fprintf(w, "\ttype plain %s\n\tdata, err := json.Marshal((*plain)(s))\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\n", structName); err != nil {
		return err
	}

	// For each choice, marshal the active case and merge
	if _, err := fmt.Fprintf(w, "\t// Start with the base object\n\tvar base map[string]json.RawMessage\n\tif err := json.Unmarshal(data, &base); err != nil {\n\t\treturn nil, err\n\t}\n\n"); err != nil {
		return err
	}

	for _, ch := range choices {
		fieldName := toCamelCaseTitle(ch.Name())
		if _, err := fmt.Fprintf(w, "\tif s.%s != nil {\n\t\tchoiceData, err := json.Marshal(s.%s)\n\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tvar choiceFields map[string]json.RawMessage\n\t\tif err := json.Unmarshal(choiceData, &choiceFields); err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tfor k, v := range choiceFields {\n\t\t\tbase[k] = v\n\t\t}\n\t}\n\n", fieldName, fieldName); err != nil {
			return err
		}
	}

	if _, err := fmt.Fprintf(w, "\treturn json.Marshal(base)\n}\n\n"); err != nil {
		return err
	}

	return nil
}

// generateChoiceUnmarshalJSON generates a custom UnmarshalJSON for structs with choice fields.
// It detects the active case by checking which JSON keys are present.
func (g *GoGenerator) generateChoiceUnmarshalJSON(structName string, choices []*schema.Choice, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// UnmarshalJSON implements json.Unmarshaler for %s.\n// Detects the active choice case by JSON key presence.\nfunc (s *%s) UnmarshalJSON(data []byte) error {\n", structName, structName); err != nil {
		return err
	}

	// Unmarshal regular fields via alias
	if _, err := fmt.Fprintf(w, "\ttype plain %s\n\tif err := json.Unmarshal(data, (*plain)(s)); err != nil {\n\t\treturn err\n\t}\n\n", structName); err != nil {
		return err
	}

	// For each choice, probe keys to detect the active case
	if _, err := fmt.Fprintf(w, "\tvar raw map[string]json.RawMessage\n\tif err := json.Unmarshal(data, &raw); err != nil {\n\t\treturn err\n\t}\n\n"); err != nil {
		return err
	}

	for _, ch := range choices {
		choiceIface := choiceGoTypeName(structName, ch.Name())
		fieldName := toCamelCaseTitle(ch.Name())

		for _, caseName := range getOrderedChildNames(ch.Children) {
			caseNode := ch.Children[caseName]
			caseType := caseGoTypeName(choiceIface, caseName)
			caseChildren := getFlatDataNodes(caseNode.GetChildren())

			// Only generate unmarshal for cases that have valid children
			var validChildren []schema.Node
			for _, child := range caseChildren {
				if g.hasValidNodes(child, false) {
					validChildren = append(validChildren, child)
				}
			}
			if len(validChildren) == 0 {
				continue
			}

			// Build condition: if any of this case's JSON keys is present
			var keys []string
			for _, child := range validChildren {
				keys = append(keys, child.Name())
			}

			if _, err := fmt.Fprintf(w, "\t// Detect case \"%s\"\n", caseName); err != nil {
				return err
			}

			// Check first key as indicator
			for i, key := range keys {
				if i == 0 {
					if _, err := fmt.Fprintf(w, "\tif _, ok := raw[\"%s\"]; ok {\n", key); err != nil {
						return err
					}
				}
			}

			if _, err := fmt.Fprintf(w, "\t\tvar c %s\n\t\tif err := json.Unmarshal(data, &c); err != nil {\n\t\t\treturn err\n\t\t}\n\t\ts.%s = &c\n\t}\n", caseType, fieldName); err != nil {
				return err
			}
		}
	}

	if _, err := fmt.Fprintf(w, "\treturn nil\n}\n\n"); err != nil {
		return err
	}

	return nil
}
