// Package protobuf provides the generator implementation for emitting Protobuf v3 files.
package protobuf

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/GabrielNunesIT/gotya/generator"
	"github.com/GabrielNunesIT/gotya/schema"
)

// Options holds configuration for the protobuf generator.
type Options struct {
	PackageName             string
	RootName                string
	GenerateFakeroot        bool
	SkipDeprecated          bool
	SkipObsolete            bool
	AddAnnotations          bool
	GenerateGetters         bool
	GenerateSetters         bool
	GeneratePopulateDefault bool
	GenerateOrderedMaps     bool
	GenerateCELValidation   bool
}

// ProtoGenerator implements the generator.Generator interface for Protobuf map generation.
type ProtoGenerator struct {
	Options           *Options
	annotatedFields   map[string]celAnnotatedField
	currentModuleName string            // name of the module currently being generated
}

// New creates a new ProtoGenerator instance.
func New(opts *Options) generator.Generator {
	if opts == nil {
		opts = &Options{}
	}
	if opts.PackageName == "" {
		opts.PackageName = "yproto" // default
	}
	if opts.RootName == "" {
		opts.RootName = "Device" // default
	}
	return &ProtoGenerator{
		Options: opts,
	}
}

// Generate writes Protobuf v3 source code for the parsed module.
func (g *ProtoGenerator) Generate(mod *schema.Module, w io.Writer) error {
	if _, err := fmt.Fprintf(w, "// Code generated by gotya. DO NOT EDIT.\nsyntax = \"proto3\";\npackage %s;\n\n", g.Options.PackageName); err != nil {
		return fmt.Errorf("failed to write package header: %w", err)
	}

	if g.Options.GenerateCELValidation {
		if _, err := fmt.Fprintf(w, "import \"buf/validate/validate.proto\";\n"); err != nil {
			return fmt.Errorf("failed to write import: %w", err)
		}
	}
	if g.Options.GeneratePopulateDefault {
		if _, err := fmt.Fprintf(w, "import \"google/protobuf/descriptor.proto\";\n\n"); err != nil {
			return fmt.Errorf("failed to write import: %w", err)
		}
		if _, err := fmt.Fprintf(w, "extend google.protobuf.FieldOptions {\n\tstring gotya_default = 50000;\n}\n"); err != nil {
			return fmt.Errorf("failed to write extension: %w", err)
		}
		if _, err := fmt.Fprintf(w, "extend google.protobuf.OneofOptions {\n\tstring gotya_oneof_default = 50000;\n}\n\n"); err != nil {
			return fmt.Errorf("failed to write extension: %w", err)
		}
	} else if g.Options.GenerateCELValidation {
		if _, err := fmt.Fprintf(w, "\n"); err != nil {
			return fmt.Errorf("failed to write newline: %w", err)
		}
	}

	if containsAnyNode([]*schema.Module{mod}) {
		if _, err := fmt.Fprintf(w, "import \"google/protobuf/any.proto\";\n"); err != nil {
			return fmt.Errorf("failed to write import: %w", err)
		}
	}

	visited := make(map[string]bool)
	for _, node := range mod.Nodes {
		if err := g.generateNode(node, w, visited); err != nil {
			return err
		}
	}
	return nil
}

// GenerateDevice takes a list of validated YANG modules, aggregates them into a single Device root struct,
// encapsulating their configurations under Module-specific messages.
func (g *ProtoGenerator) GenerateDevice(modules []*schema.Module, w io.Writer) error {
	// Reset annotation tracking for this generation call.
	g.annotatedFields = make(map[string]celAnnotatedField)

	if _, err := fmt.Fprintf(w, "// Code generated by gotya. DO NOT EDIT.\nsyntax = \"proto3\";\npackage %s;\n\n", g.Options.PackageName); err != nil {
		return fmt.Errorf("failed to write package header: %w", err)
	}

	if g.Options.GenerateCELValidation {
		if _, err := fmt.Fprintf(w, "import \"buf/validate/validate.proto\";\n"); err != nil {
			return fmt.Errorf("failed to write import: %w", err)
		}
	}
	if g.Options.GeneratePopulateDefault {
		if _, err := fmt.Fprintf(w, "import \"google/protobuf/descriptor.proto\";\n\n"); err != nil {
			return fmt.Errorf("failed to write import: %w", err)
		}
		if _, err := fmt.Fprintf(w, "extend google.protobuf.FieldOptions {\n\tstring gotya_default = 50000;\n}\n"); err != nil {
			return fmt.Errorf("failed to write extension: %w", err)
		}
		if _, err := fmt.Fprintf(w, "extend google.protobuf.OneofOptions {\n\tstring gotya_oneof_default = 50000;\n}\n\n"); err != nil {
			return fmt.Errorf("failed to write extension: %w", err)
		}
	} else if g.Options.GenerateCELValidation {
		if _, err := fmt.Fprintf(w, "\n"); err != nil {
			return fmt.Errorf("failed to write newline: %w", err)
		}
	}

	if containsAnyNode(modules) {
		if _, err := fmt.Fprintf(w, "import \"google/protobuf/any.proto\";\n"); err != nil {
			return fmt.Errorf("failed to write import: %w", err)
		}
	}

	visited := make(map[string]bool)
	type moduleNode struct {
		moduleName string
		node       schema.Node
	}
	var allTopLevelNodes []moduleNode

	if g.Options.GenerateFakeroot {
		if _, err := fmt.Fprintf(w, "message %s {\n", g.Options.RootName); err != nil {
			return fmt.Errorf("write err: %w", err)
		}

		fieldIndex := 1
		for _, mod := range modules {
			if len(mod.Nodes) == 0 {
				continue // skip empty modules
			}

			modMsgName := toCamelCaseTitle(mod.Name)
			fieldName := convertToSnakeCase(mod.Name)
			if _, err := fmt.Fprintf(w, "\t%s %s = %d;\n", modMsgName, fieldName, fieldIndex); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			fieldIndex++
		}
		if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
	}

	for _, mod := range modules {
		if len(mod.Nodes) == 0 {
			continue
		}

		g.currentModuleName = mod.Name

		modMsgName := toCamelCaseTitle(mod.Name)
		if visited[modMsgName] {
			continue
		}
		visited[modMsgName] = true

		if _, err := fmt.Fprintf(w, "message %s {\n", modMsgName); err != nil {
			return fmt.Errorf("write err: %w", err)
		}

		if err := g.generateEnumBlocks(mod.Nodes, w); err != nil {
			return err
		}

		modFieldIndex := 1
		for _, childName := range getSortedChildNames(mod.Nodes) {
			child := mod.Nodes[childName]
			if g.shouldSkip(child) {
				continue
			}
			allTopLevelNodes = append(allTopLevelNodes, moduleNode{moduleName: mod.Name, node: child}) // collect for deep generations
			if err := g.generateField(child, w, &modFieldIndex); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
	}

	for _, modNode := range allTopLevelNodes {
		g.currentModuleName = modNode.moduleName
		if err := g.generateNode(modNode.node, w, visited); err != nil {
			return err
		}
		if choice, ok := modNode.node.(*schema.Choice); ok {
			for _, caseName := range getSortedChildNames(choice.Children) {
				caseNode := choice.Children[caseName]
				if c, ok := caseNode.(*schema.Case); ok {
					if err := g.generateCaseMessage(c, w, visited); err != nil {
						return err
					}
				}
			}
		}
	}

	// Emit service blocks — one per module that contains at least one RPC or Action.
	// Actions may be nested inside containers/lists, so we collect them recursively.
	for _, mod := range modules {
		var rpcMethods []string
		var collectRPCActions func(nodes map[string]schema.Node)
		collectRPCActions = func(nodes map[string]schema.Node) {
			for _, name := range getSortedChildNames(nodes) {
				node := nodes[name]
				switch n := node.(type) {
				case *schema.RPC:
					rpcPrefix := toCamelCaseTitle(n.Name())
					rpcMethods = append(rpcMethods, fmt.Sprintf("\trpc %s(%sInput) returns (%sOutput);\n",
						rpcPrefix, rpcPrefix, rpcPrefix))
				case *schema.Action:
					rpcPrefix := toCamelCaseTitle(n.Name())
					rpcMethods = append(rpcMethods, fmt.Sprintf("\trpc %s(%sInput) returns (%sOutput);\n",
						rpcPrefix, rpcPrefix, rpcPrefix))
				case *schema.Container, *schema.List:
					collectRPCActions(node.GetBase().Children)
				}
			}
		}
		collectRPCActions(mod.Nodes)
		if len(rpcMethods) > 0 {
			svcName := toCamelCaseTitle(mod.Name) + "Service"
			if _, err := fmt.Fprintf(w, "service %s {\n", svcName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			for _, m := range rpcMethods {
				if _, err := fmt.Fprint(w, m); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
			if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}

	// CEL path validation: verify all annotated fields exist in the schema.
	if g.Options.GenerateCELValidation {
		if errs := collectCELPathErrors(modules, g.annotatedFields); len(errs) > 0 {
			return fmt.Errorf("CEL path validation failed:\n%s", strings.Join(errs, "\n"))
		}
	}

	return nil
}

func (g *ProtoGenerator) generateNode(node schema.Node, w io.Writer, visited map[string]bool) error {
	switch n := node.(type) {
	case *schema.Container:
		return g.generateMessage(n.Name(), n.Description, n.Children, w, visited)
	case *schema.List:
		return g.generateMessage(n.Name(), n.Description, n.Children, w, visited)
	case *schema.RPC, *schema.Action:
		base := node.GetBase()
		rpcPrefix := toCamelCaseTitle(base.NodeName)
		if inputNode, ok := base.Children["input"]; ok {
			if inp, ok2 := inputNode.(*schema.Input); ok2 {
				if err := g.generateMessage(rpcPrefix+"Input", nil, inp.Children, w, visited); err != nil {
					return err
				}
			}
		}
		if outputNode, ok := base.Children["output"]; ok {
			if out, ok2 := outputNode.(*schema.Output); ok2 {
				if err := g.generateMessage(rpcPrefix+"Output", nil, out.Children, w, visited); err != nil {
					return err
				}
			}
		}
		return nil
	case *schema.Notification:
		notifMsgName := toCamelCaseTitle(n.Name()) + "Notification"
		desc := n.GetBase().Description
		return g.generateMessage(notifMsgName, desc, n.GetBase().Children, w, visited)
	}
	return nil
}

func (g *ProtoGenerator) shouldSkip(node schema.Node) bool {
	base := node.GetBase()
	if g.Options.SkipDeprecated && base.Status != nil && *base.Status == "deprecated" {
		return true
	}
	if g.Options.SkipObsolete && base.Status != nil && *base.Status == "obsolete" {
		return true
	}
	return false
}

func (g *ProtoGenerator) generateMessage(name string, description *string, children map[string]schema.Node, w io.Writer, visited map[string]bool) error {
	msgName := toCamelCaseTitle(name)
	if visited[msgName] {
		return nil
	}
	visited[msgName] = true

	if g.Options.AddAnnotations && description != nil && *description != "" {
		descLines := strings.Split(strings.TrimSpace(*description), "\n")
		for _, line := range descLines {
			if _, err := fmt.Fprintf(w, "// %s\n", strings.TrimSpace(line)); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}

	if _, err := fmt.Fprintf(w, "message %s {\n", msgName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	if err := g.generateEnumBlocks(children, w); err != nil {
		return err
	}

	fieldIndex := 1
	for _, childName := range getSortedChildNames(children) {
		child := children[childName]
		if g.shouldSkip(child) {
			continue
		}
		if err := g.generateField(child, w, &fieldIndex); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	// Recurse for nested messages
	for _, childName := range getSortedChildNames(children) {
		child := children[childName]
		if g.shouldSkip(child) {
			continue
		}
		if err := g.generateNode(child, w, visited); err != nil {
			return err
		}
		// Also handle nested cases if any
		if choice, ok := child.(*schema.Choice); ok {
			for _, caseName := range getSortedChildNames(choice.Children) {
				caseNode := choice.Children[caseName]
				if c, ok := caseNode.(*schema.Case); ok {
					if err := g.generateCaseMessage(c, w, visited); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

func (g *ProtoGenerator) generateCaseMessage(n *schema.Case, w io.Writer, visited map[string]bool) error {
	// A case needs its own message if it contains multiple items or nested structures to be serialized as oneof payload
	msgName := toCamelCaseTitle(n.Name()) + "Case"
	if visited[msgName] {
		return nil
	}
	visited[msgName] = true

	if _, err := fmt.Fprintf(w, "message %s {\n", msgName); err != nil {
		return fmt.Errorf("write err: %w", err)
	}
	fieldIndex := 1
	for _, childName := range getSortedChildNames(n.Children) {
		child := n.Children[childName]
		if g.shouldSkip(child) {
			continue
		}
		if err := g.generateField(child, w, &fieldIndex); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(w, "}\n\n"); err != nil {
		return fmt.Errorf("write err: %w", err)
	}

	for _, childName := range getSortedChildNames(n.Children) {
		child := n.Children[childName]
		if g.shouldSkip(child) {
			continue
		}
		if err := g.generateNode(child, w, visited); err != nil {
			return err
		}
	}
	return nil
}

func (g *ProtoGenerator) generateField(node schema.Node, w io.Writer, fieldIndex *int) error {
	fieldName := convertToSnakeCase(node.Name())
	var protoType string

	if g.Options.AddAnnotations && node.GetBase().Description != nil && *node.GetBase().Description != "" {
		descLines := strings.Split(strings.TrimSpace(*node.GetBase().Description), "\n")
		for _, line := range descLines {
			if _, err := fmt.Fprintf(w, "\t// %s\n", strings.TrimSpace(line)); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}

	switch n := node.(type) {
	case *schema.Leaf:
		var opts []string
		if g.Options.GenerateCELValidation {
			validateOpt := buildValidateOptions(n.Type, false, mapYANGTypeToProto(n.Type.Name))
			if validateOpt != "" {
				opts = append(opts, validateOpt)
				// Track by proto field name for CEL path validation.
				if g.annotatedFields != nil {
					key := fmt.Sprintf("%s:%s:%d", g.currentModuleName, fieldName, *fieldIndex)
					g.annotatedFields[key] = celAnnotatedField{ModuleName: g.currentModuleName, ProtoFieldName: fieldName, SchemaNodeName: n.Name()}
				}
			}
		}

		if g.Options.GeneratePopulateDefault && n.Default != nil {
			opts = append(opts, fmt.Sprintf("(gotya_default) = %q", *n.Default))
		}

		var validateOptsStr string
		if len(opts) > 0 {
			validateOptsStr = " [" + strings.Join(opts, ", ") + "]"
		}

		if len(n.Type.Length) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: length %v\n", n.Type.Length); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if len(n.Type.Range) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: range %v\n", n.Type.Range); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if len(n.Type.Pattern) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: pattern %v\n", n.Type.Pattern); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if n.Type.Name == "enumeration" && len(n.Type.Enums) > 0 {
			protoType = toCamelCaseTitle(n.Name())
			if g.Options.GeneratePopulateDefault && n.Default != nil {
				// Determine if we need to set the value mapping to an enum key or raw string. Typically Enum default is the raw string of the enum identifier
				// To keep it simple, we treat enum custom defaults like strings.
				validateOptsStr = fmt.Sprintf(" [(gotya_default) = %q]", *n.Default)
			} else {
				validateOptsStr = "" // No protovalidate options for enum types natively
			}
		} else {
			protoType = mapYANGTypeToProto(n.Type.Name)
		}
		if _, err := fmt.Fprintf(w, "\t%s %s = %d%s;\n", protoType, fieldName, *fieldIndex, validateOptsStr); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.LeafList:
		var opts []string
		if g.Options.GenerateCELValidation {
			validateOpt := buildValidateOptions(n.Type, true, mapYANGTypeToProto(n.Type.Name))
			if validateOpt != "" {
				opts = append(opts, validateOpt)
				// Track by proto field name for CEL path validation.
				if g.annotatedFields != nil {
					key := fmt.Sprintf("%s:%s:%d", g.currentModuleName, fieldName, *fieldIndex)
					g.annotatedFields[key] = celAnnotatedField{ModuleName: g.currentModuleName, ProtoFieldName: fieldName, SchemaNodeName: n.Name()}
				}
			}
		}

		var validateOptsStr string
		if len(opts) > 0 {
			validateOptsStr = " [" + strings.Join(opts, ", ") + "]"
		}

		if len(n.Type.Length) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: length %v\n", n.Type.Length); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if len(n.Type.Range) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: range %v\n", n.Type.Range); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		if len(n.Type.Pattern) > 0 {
			if _, err := fmt.Fprintf(w, "\t// constraints: pattern %v\n", n.Type.Pattern); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		protoType = "repeated " + mapYANGTypeToProto(n.Type.Name)
		if _, err := fmt.Fprintf(w, "\t%s %s = %d%s;\n", protoType, fieldName, *fieldIndex, validateOptsStr); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.Container:
		protoType = toCamelCaseTitle(n.Name())
		if _, err := fmt.Fprintf(w, "\t%s %s = %d;\n", protoType, fieldName, *fieldIndex); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.List:
		protoType = "repeated " + toCamelCaseTitle(n.Name())
		if _, err := fmt.Fprintf(w, "\t%s %s = %d;\n", protoType, fieldName, *fieldIndex); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.Choice:
		if _, err := fmt.Fprintf(w, "\toneof %s {\n", fieldName); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		if g.Options.GeneratePopulateDefault && n.Default != nil {
			if _, err := fmt.Fprintf(w, "\t\toption (gotya_oneof_default) = %q;\n", *n.Default); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
		for _, caseName := range getSortedChildNames(n.Children) {
			if _, ok := n.Children[caseName].(*schema.Case); !ok {
				continue
			}
			if g.shouldSkip(n.Children[caseName]) {
				continue
			}
			caseFieldName := convertToSnakeCase(caseName)
			caseMsgName := toCamelCaseTitle(caseName) + "Case"
			if _, err := fmt.Fprintf(w, "\t\t%s %s = %d;\n", caseMsgName, caseFieldName, *fieldIndex); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			*fieldIndex++
		}
		if _, err := fmt.Fprintf(w, "\t}\n"); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
	case *schema.AnyData, *schema.AnyXML:
		if _, err := fmt.Fprintf(w, "\tgoogle.protobuf.Any %s = %d;\n", fieldName, *fieldIndex); err != nil {
			return fmt.Errorf("write err: %w", err)
		}
		*fieldIndex++
	case *schema.RPC, *schema.Action, *schema.Notification:
		// These are not proto message fields — skipped here, handled as service blocks / messages in GenerateDevice
		return nil
	}

	return nil
}

func (g *ProtoGenerator) generateEnumBlocks(children map[string]schema.Node, w io.Writer) error {
	for _, childName := range getSortedChildNames(children) {
		child := children[childName]
		if leaf, ok := child.(*schema.Leaf); ok && leaf.Type.Name == "enumeration" && len(leaf.Type.Enums) > 0 {
			enumName := toCamelCaseTitle(leaf.Name())
			if _, err := fmt.Fprintf(w, "\tenum %s {\n", enumName); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
			for i, enumVal := range leaf.Type.Enums {
				enumValName := fmt.Sprintf("%s_%s", strings.ToUpper(convertToSnakeCase(enumName)), strings.ToUpper(convertToSnakeCase(enumVal)))
				if _, err := fmt.Fprintf(w, "\t\t%s = %d;\n", enumValName, i); err != nil {
					return fmt.Errorf("write err: %w", err)
				}
			}
			if _, err := fmt.Fprintf(w, "\t}\n"); err != nil {
				return fmt.Errorf("write err: %w", err)
			}
		}
	}
	return nil
}

func toCamelCaseTitle(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func convertToSnakeCase(s string) string {
	return strings.ReplaceAll(strings.ToLower(s), "-", "_")
}

func mapYANGTypeToProto(yangType string) string {
	switch yangType {
	case "int8", "int16", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "uint8", "uint16", "uint32":
		return "uint32"
	case "uint64":
		return "uint64"
	case "boolean":
		return "bool"
	case "decimal64":
		return "double"
	case "empty":
		return "bool"
	case "binary":
		return "bytes"
	default:
		return "string"
	}
}

func getSortedChildNames(children map[string]schema.Node) []string {
	names := make([]string, 0, len(children))
	for name := range children {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// containsAnyNode reports whether any module in modules contains an anydata or anyxml node (recursive).
func containsAnyNode(modules []*schema.Module) bool {
	for _, mod := range modules {
		if moduleHasAny(mod.Nodes) {
			return true
		}
	}
	return false
}

// moduleHasAny recursively checks whether nodes contains any *schema.AnyData or *schema.AnyXML node.
func moduleHasAny(nodes map[string]schema.Node) bool {
	for _, node := range nodes {
		switch node.(type) {
		case *schema.AnyData, *schema.AnyXML:
			return true
		}
		if moduleHasAny(node.GetChildren()) {
			return true
		}
	}
	return false
}
